### DISCUSSION TITLE
How to apply local fixes when using DarkReader programmatically?

### DISCUSSION THREAD

**Discussion by brunnerh** [darkreader/darkreader#11429] [Q&A]
If I try to change things in a stylesheet using `[data-darkreader-scheme="dark"] ...`, said stylesheet will also be affected by DR, essentially breaking it.

Is there a way to make DarkReader ignore a stylesheet and let it apply as is or another way to apply fixes?

**Comment by bershanskiy** [comment]
Could you please clarify what you are trying to do? E.g., are you using Dark Reader extension or library/`npm` module? Is this your own site?

In general, the easiest way to force a particular look is to add a style with `!important`, but it may not be maintainable in the long term.

**Reply by brunnerh** [reply]
It is my own site and I am using the module (hence the title).

To give a concrete example (where `!important` will not do anything), trying to use a given generated color:

```css
[data-darkreader-scheme="dark"] .sitemap-node {
    border-color: var(--darkreader-bg--sitemap-side-background) !important;
}
```

DarkReader re-writes the variable reference, breaking it:

```css
[data-darkreader-scheme="dark"] .sitemap-node {
    border-color: var(--darkreader-border--darkreader-bg--sitemap-side-background) !important;
}
```

---

Maybe this is also just a bug, because DarkReader changes the background but not the border, hence the above attempt to fix it.

The original properties for the nodes are:
```css
background: var(--sitemap-side-background);
color: var(--blue-dark);
border: 1px solid var(--sitemap-side-background);
border-width: 1px 0;
```

And DarkReader only generates :
```css
color: var(--darkreader-text--blue-dark);
background: var(--darkreader-bg--sitemap-side-background);
```
Thus leaving bright borders around the items.
