### DISCUSSION TITLE
dark reader does not work on canvas - Google Chrome

### DISCUSSION THREAD

**Discussion by NeedA-Dream** [darkreader/darkreader#12493] [General]
Hi,
I used Dark mode last year and I did not have any issue. But after the update, document background like pdf and word appear So white which hurts my eyes. I have tried to fix the problem but no luck.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
