### DISCUSSION TITLE
DarkReader is messing with the Tailwind styles on very important elements on my site

### DISCUSSION THREAD

**Discussion by justinfarrelldev** [darkreader/darkreader#13106] [Q&A]
Hello, first of all I would like to say thank you for creating DarkReader - I use it every day! 

This has had me wracking my brain for a while.

I am using the following Tailwind styles on some `span` tags for a pretty sweet text gradient effect (which is used pretty frequently on my site): 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.text-gradient {
    @apply inline-block bg-gradient-to-r from-sky-600 to-success bg-clip-text font-semibold text-transparent !important;
}
```

The gradient normally looks like this: 
![image](https://github.com/user-attachments/assets/7d2e7293-d1e2-4aef-8854-fe3d50d74934)

The issue I have encountered is that the gradient is not rendered when DarkReader is enabled, meaning the text turns invisible (as it is set as transparent for the effect above):
![image](https://github.com/user-attachments/assets/71bd8853-be6d-4ef3-81c7-16ed76e40fbe)

I have managed to narrow it down to this class in the inspector: 
![image](https://github.com/user-attachments/assets/0e55785c-5af3-481a-a192-b5dba576debe)

If I uncheck that box, all of the text looks as it should.

Is there any solution you can think of for this? I would love it if there was some way to tell DarkReader to ignore that particular style and leave it be (as I've already programmed this site with dark mode in mind).

Thank you!

**Comment by spector700** [comment]
Did you figure this out, I am having the same thing?

**Reply by justinfarrelldev** [reply]
Unfortunately, no. Hoping someone can come in and clear this up

**Comment by witalij777** [comment]
Hi, when you use DarkReader on your site in your tag <html> have this attributes -> 
`<html dir="ltr" lang="pl-PL" data-darkreader-mode="dynamic" data-darkreader-scheme="dark" data-darkreader-proxy-injected="true" data-previous-scroll-y="-0px" class="sp-message-open">`

My solution:
Check if attribute (like data-darkreader-scheme) exist and off your linear-gradient (use simple bold font)
It's NOT PERFECT solution... but you dont have error in your site and you still have BEST dark_mode on you site :)

Best Regards!

**Comment by spector700** [comment]
Thanks, I also did a workaround for this. I added a class to the main.css file using `linear-gradient`:

```css
  .title-gradient {
    background: rgb(82, 129, 222);
    background: -moz-linear-gradient(
      90deg,
      rgba(82, 129, 222, 1) 0%,
      rgba(136, 191, 205, 1) 44%,
      rgba(131, 180, 196, 1) 63%,
      rgba(59, 92, 213, 1) 100%
    );
    background: -webkit-linear-gradient(
      90deg,
      rgba(82, 129, 222, 1) 0%,
      rgba(136, 191, 205, 1) 44%,
      rgba(131, 180, 196, 1) 63%,
      rgba(59, 92, 213, 1) 100%
    );
    background: linear-gradient(
      90deg,
      rgba(82, 129, 222, 1) 0%,
      rgba(136, 191, 205, 1) 44%,
      rgba(131, 180, 196, 1) 63%,
      rgba(59, 92, 213, 1) 100%
    );
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#5281de",endColorstr="#3b5cd5",GradientType=1);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }
```

Then I use the class directly:

```html
    <h1 className="title-gradient text-4xl font-bold text-balance sm:text-6xl">Gradient Lmaooo</h1>
```

Then with dark reader on, It makes the gradient a bit darker like the rest of the site and is still visible.
