### DISCUSSION TITLE
How can I disable dark-reader from styling the scrollbar (or a single element) of the Chrome extension that I wrote?

### DISCUSSION THREAD

**Discussion by bzmind** [darkreader/darkreader#13358] [Q&A]
Hi,
I've created an extension with custom styled scrollbar, and I don't want it to be tampered by the dark reader extension on the user's browser using my extension, I basically need something like the `<meta name="darkreader-lock">` but only for the scrollbar in this case, but also, it would be really nice if there was a feature to disable dark-reader on a single element like a `div`, since my extension adds some elements to the DOM when user clicks on some stuff, and it doesn't have any `head` tag to use the `<meta name="darkreader-lock">`, so that would ALSO solve the issue with scrollbar too, **in fact, that would be even better.**
I also did try to override everything with `!important` but it doesn't have ANY effect at all...
```css
.jfk-bubble.gtx-bubble::-webkit-scrollbar-button {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-thumb {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-track {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-track-piece {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-corner {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-resizer {
  all: unset !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-thumb {
  border: 7px solid rgba(0, 0, 0, 0) !important;
  background-clip: padding-box !important;
  border-radius: 10000px !important;
  background-color: #d3d3d3 !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar-thumb:hover {
  border: 7px solid rgba(0, 0, 0, 0) !important;
  background-clip: padding-box !important;
  border-radius: 10000px !important;
  background-color: #7a7a7a !important;
}

.jfk-bubble.gtx-bubble::-webkit-scrollbar {
  width: 21px !important;
  background-color: transparent !important;
}
```
