### DISCUSSION TITLE
Wrong background color until toggling mode

### DISCUSSION THREAD

**Discussion by non-bin** [darkreader/darkreader#14405] [General]
I'm having trouble fixing this site (there's lots more pages but they need a login)
https://my.gov.au/en/services/raising-kids

It works when switching darkreader from light to dark, or pressing apply on the theme editor, but when loading or reloading the page it reverts to the white cards.

I've tried targeting the elements directly:

```css
.card {
    background-color: var(--darkreader-bg--greyLight, var(--darkreader-background-ffffff, #181a1b)) !important;
}
```

or changing the variable

```css
:root {
    --mygov-background-color-secondary: var(--darkreader-neutral-background) !important;
}
```

with no change. Maybe it's being reset with js? Any suggestions on how I can break on a style being changed?
