### DISCUSSION TITLE
Disable Dark Reader on my website

### DISCUSSION THREAD

**Discussion by joelnedev** [darkreader/darkreader#6868] [Q&A] [answered]
Hi,
I have a website that's already in dark mode, and Dark Reader breaks my CSS. Is there anything I can do to prevent Dark Reader from being enabled on my site by default, or will users have to figure it out on their own?

**Comment by bershanskiy** [comment]
What is the domain of your website? I'll add it to the list of known dark websites and Dark Reader will do nothing when user opens website.

**Comment by imsys** [comment]
This is a bigger topic I think.
We can use Media Queries to detect user preference for light or dark theme.  

```css
@media (prefers-color-scheme: light) {
    body {
        background-color: white;
        color: black;
    }
}
@media (prefers-color-scheme: dark) {
    body {
        background-color: black;
        color: white;
    }
}
```

Or get it thought javascript
```js
window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
```

I would initially say that Dark Reader could look for the existence of prefers-color-scheme, and if those were there, it would take it as the website has support for Dark Theme automatically, and maybe not do changes to it. Idk if it would be too performance intensive.
Just if Dark Reader is enabled, it would force setting prefers-color-scheme to dark.

or maybe we could just set a global variable in JS, and the Dark Reader would look for it:
window.DarkModeImplemented = true
or:
window.DarkReaderFriendly = true
or
window.DarkReaderDisable = true

But I see the plugin has more than just just turning making the theme dark, it has brightness, contrast and all other features. Maybe the dark theme we as a webdev create are not as much nice as the user wants, and they would want to overwrite the site css.

So, at the end, I think there should be just a better documentation on how we can make Dark Reader play nicer on our website.
