### DISCUSSION TITLE
How do i enable dark mode in PDF?

### DISCUSSION THREAD

**Discussion by bdmariobd** [darkreader/darkreader#7154] [Q&A] [answered]
I'm using firefox extension.

**Comment by Gusted** [comment, marked as answer]
It's not possible to enable the dark mode on PDF's within Firefox. It's a security restriction from Firefox.

**Reply by bdmariobd** [reply]
Oh, didn't know. 
Now I see that in the older verison of DarkReader it's more clear that issue:
![imagen](https://user-images.githubusercontent.com/56127361/138327954-6d683ac6-4d9f-4895-b431-2e9a876bbd0b.png)
It means: this page is protected by the navigator. 
While in new version, it only says: 
![imagen](https://user-images.githubusercontent.com/56127361/138327698-5b4f240a-f67b-4e60-95ff-257d4f2186c0.png)
I feel that it was more clear in older version. Maybe is this an issue?

**Reply by Gusted** [reply]
> I feel that it was more clear in older version. Maybe is this an issue?

Definitely, @alexanderby We should have that protected by browser UI Element back in the new design.

**Comment by alexanderby** [comment]
Oh, I missed it

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```

**Reply by JianingZhangnan** [reply]
I have a better solution for firefox(I think):

```css
@media (prefers-color-scheme: dark) {
    .pdfViewer .page canvas {
      filter: invert(0.9) hue-rotate(180deg) !important;
    }
  }
```
It change PDF only and do not have an effect on other things.
