### DISCUSSION TITLE
First time trying to make a fix to website

### DISCUSSION THREAD

**Discussion by paniash** [darkreader/darkreader#7902] [Q&A] [answered]
Hi!

I'm trying to make a fix for a website for the first time and am stuck really. Following the instructions in `CONTRIBUTING.md`, I'm trying to change the background color for: https://www.physics.utoronto.ca/~aephraim/aephraim.html#outline

Adding the following to the dynamic theme editor:
```css
================================

www.physics.utoronto.ca/~aephraim/aephraim.html

CSS
body {           
    background-color: var(--darkreader-neutral-background) !important;
}
```

I don't see any changes when hitting **Apply**. I'd be glad if someone could point out the mistake I'm making.
