### DISCUSSION TITLE
Extension does not work in PDFs in firefox

### DISCUSSION THREAD

**Discussion by IvanRenison** [darkreader/darkreader#8018] [Q&A] [answered]
The extension seems to not work in PDF files in firefox, I have seen #7154, but I wanted to know if it is still really not possible? Because some other extensions (for example https://addons.mozilla.org/es/firefox/addon/to-google-translate/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-collection-featured) do work in PDFs

**Comment by Gusted** [comment, marked as answer]
> The extension seems to not work in PDF files in firefox, I have seen #7154, but I wanted to know if it is still really not possible? Because some other extensions (for example https://addons.mozilla.org/es/firefox/addon/to-google-translate/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-collection-featured) do work in PDFs

Those extensions do not function to the same extent as Dark Reader does. The linked extension only requires context menu access on those pages which is possible on PDF's, Dark Reader on the other hand need to have access to the page as a whole in order to function.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
