### DISCUSSION TITLE
Possible to handle CSS-referenced Data URI SVG images?

### DISCUSSION THREAD

**Discussion by UweKeim** [darkreader/darkreader#9202] [General]
I'm using the JavaScript version of Dark Reader on my own website.

When using the Bootstrap 5.x [Accordion control](https://getbootstrap.com/docs/5.1/components/accordion/#flush), I just figured out that the expand/collapse arrows come from a CSS `background-image` URL:

```css
.accordion-button::after {
    background-image: url(data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23212529'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e);
}
```

This looks great when having the original mode without Dark Reader:

![image](https://user-images.githubusercontent.com/415439/177394555-d97ea8fe-2de4-4b21-8be8-b1e89a87e318.png)

When having Dark Reader activated, they are nearly unreadable:

![image](https://user-images.githubusercontent.com/415439/177404357-555f123e-d05b-475d-a15e-bea2b5c46cc4.png)

I know that I can [add filters to match certain `img` tags](https://github.com/darkreader/darkreader/discussions/7577#discussioncomment-2919458) via the `invert` option:

```javascript
DarkReader.enable({
      brightness: 100,
      contrast: 100,
      sepia: 0
}, {invert: ['img[src*=".svg"]']});
```

But I'm not sure whether this (or another) technique is usable to tell Dark Reader to invert the color of an SVG image, attached to a `background-image` CSS property.

### My question

Is there any way to configure Dark Reader to handle CSS background SVG images coming from a Data URI?

**Comment by Gusted** [comment]
Hi @UweKeim!

That's currently not possible. In order to analyze SVG's, Dark Reader must know the DOM structure(as it inspects/analyze each element of the SVG differently). However this not the case with inlining the DOM structure and parsing HTML code into a DOM structure is a PITA.

> Is there any way to configure Dark Reader to handle CSS background SVG images coming from a Data URI?

Not really, the best thing you can do is to tell Dark Reader to invert that img. So your workaround is the best solution to this problem.

**Comment by UweKeim** [comment]
OK, I've used the following workaround.

I've added another SCSS "bootstrap-overrides.scss" file into my CSS pipeline that is placed _after_ the Bootstrap styles.

In this new SCSS file, I've inserted the following content:

```scss
$bc-dark-accordion-icon-color: #908D89;
$bc-dark-accordion-button-icon: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='#{$bc-dark-accordion-icon-color}'><path fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/></svg>") !default;

@media(prefers-color-scheme:dark) {
    .accordion-button {
        &::after {
            background-image: escape-svg($bc-dark-accordion-button-icon);
        }
    }
}
```

I've changed the color to `#C7C0B5`.

After this change, the Bootstrap 5.x Accordion looks great in dark mode, too 😊
