### ISSUE TITLE
[Broken Website] www.virustotal.com

### ISSUE THREAD

**Issue by zedtran** [darkreader/darkreader#10520]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

DarkReader default setting enabled for `www.virustotal.com` are non-functional or not rendering dark theme as expected.

The site appears to have a native color scheme selector via the HTML ``:root`` attribute ``data-bs-theme`` which can be toggled to either "``dark``" or "``light``".

```html
<html data-bs-theme="light" data-darkreader-mode="dynamic" data-darkreader-scheme="dark" lang="en">
    ...
</html>
```

When the value for this attribute is manually edited to "``dark``", the CSS element properties are dynamically populated using relevant site properties for the "_dark_" color scheme.

```css
html[data-bs-theme="dark"] { ... }
```

I was able to implement the site's document properties for its dark theme from the CSS dynamic theme editing settings in DarkReader DevTools. I appended these CSS selector settings to the ``:root`` pseudo-class shown in the CSS segment below. There may be other solutions. This is just the way I did it. So, please forgive me if I showed my front-end rookie card, if there's a better alternative. (**Note**: _Of course, one could also modify the pre-existing CSS ``:root`` selector like "``:root[data-bs-theme="light"]``", but I wanted to add the segment to differentiate my changes_).

```css
html[data-bs-theme="light"] {
  color-scheme: dark;
  --bs-disabled-color: #576175;
  --bs-body-bg: #272e3f;
  --bs-body-bg-rgb: 39, 46, 63;
  --bs-body-color: #ffffff;
  --bs-body-color-rgb: 255, 255, 255;
  --bs-secondary-color: #d3d7de;
  --bs-secondary-color-rgb: 211, 215, 222;
  --bs-secondary-bg: #313a4e;
  --bs-secondary-bg-rgb: 49, 58, 78;
  --bs-tertiary-color: #a7aebe;
  --bs-tertiary-color-rgb: 167, 174, 190;
  --bs-tertiary-bg: #414d68;
  --bs-tertiary-bg-rgb: 65, 77, 104;
  --bs-primary: #86aaf9;
  --bs-primary-rgb: 134, 170, 249;
  --bs-primary-bg: #3e4f74;
  --bs-primary-color: #cfddfc;
  --bs-danger: #ff667f;
  --bs-danger-rgb: 255, 102, 127;
  --bs-danger-bg: #4d3337;
  --bs-danger-color: #ffccd4;
  --bs-warning: #f5993d;
  --bs-warning-rgb: 245, 153, 61;
  --bs-warning-bg: #43403d;
  --bs-warning-color: #facc9e;
  --bs-success: #00e5b9;
  --bs-success-rgb: 0, 229, 185;
  --bs-success-bg: #21453e;
  --bs-success-color: #4cffdd;
  --bs-info-bg: #66b8ff;
  --bs-info-rgb: 102, 184, 255;
  --bs-info-bg: #2c4153;
  --bs-info-color: #cce7ff;
  --bs-border-color: #495674;
  --bs-input-border-color: #58698d;
  --bs-code-color: var(--bs-tertiary-color);
  --bs-form-feedback-icon-valid: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 fill=%27%2300e5b9%27 viewBox=%270 0 8 8%27%3e%3cpath d=%27M2.3 6.73.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z%27/%3e%3c/svg%3e");
  --bs-form-feedback-icon-invalid: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 stroke=%27%23ff6680%27 viewBox=%270 0 12 12%27 width=%2712%27 height=%2712%27 fill=%27none%27 %3e%3ccircle cx=%276%27 cy=%276%27 r=%274.5%27/%3e%3cpath stroke-linejoin=%27round%27 d=%27M5.8 3.6h.4L6 6.5z%27/%3e%3ccircle cx=%276%27 cy=%278.2%27 r=%27.6%27 fill=%27%23d9534f%27 stroke=%27none%27/%3e%3c/svg%3e");
  --bs-accordion-btn-icon: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 16 16%27 fill=%27%23f6f7f9%27%3e%3cpath fill-rule=%27evenodd%27 d=%27M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z%27/%3e%3c/svg%3e");
  --bs-accordion-btn-active-icon: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 16 16%27 fill=%27%23f6f7f9%27%3e%3cpath fill-rule=%27evenodd%27 d=%27M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z%27/%3e%3c/svg%3e");
  --bs-form-check-input-checked-bg-image: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 20 20%27%3e%3cpath fill=%27none%27 stroke=%27%23272E3F%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27 stroke-width=%273%27 d=%27m6 10 3 3 6-6%27/%3e%3c/svg%3e");
  --bs-form-check-radio-checked-bg-image: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%27-4 -4 8 8%27%3e%3ccircle r=%272%27 fill=%27%23272E3F%27/%3e%3c/svg%3e");
  --bs-form-check-input-indeterminate-bg-image: url("data:image/svg+xml,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 20 20%27%3e%3cpath fill=%27none%27 stroke=%27%23272E3F%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27 stroke-width=%273%27 d=%27M6 10h8%27/%3e%3c/svg%3e");
  --bs-btn-back-filter: invert(1) grayscale(100%) brightness(200%);
  --bs-btn-close-filter: invert(1) grayscale(100%) brightness(200%);
}
```

### Website Address

https://www.virustotal.com

### Steps To Reproduce

1. Navigate to `www.virustotal.com`
2. Enable DarkReader for the site

### Operating System

Windows 10 Pro (22H2)

### Web Browser name and version

Firefox Version 108.0.1 (64-bit)

### Dark Reader version

4.9.60
