### ISSUE TITLE
[Broken Website] zhixue.com

### ISSUE THREAD

**Issue by DeepChirp** [darkreader/darkreader#11142]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I don't know how to handle it. If I directly add `.report_hd`, then the text will be overwritten. But this background image cannot be directly removed.
The code is as follows:
```css
.report_bd {
	background:#fff;
	width: 939px;
	margin-left: 10px;
}

.report_hd {
	background: url('https://static.zhixue.com/zhixuebao/public/202130/module/global/images/report.png') no-repeat left top;
	height: 58px;
}

.report-hd {
	background: url('https://static.zhixue.com/zhixuebao/public/202130/module/global/images/report.png') no-repeat left top;
	height: 17px;
}
```
![image](https://user-images.githubusercontent.com/66902050/232539268-8d1e21b8-e4db-4fec-81a6-f793f68e227e.png)

### Website Address

https://www.zhixue.com/

### Steps To Reproduce

_No need_

### Operating System

_No need_

### Web Browser name and version

_No need_

### Dark Reader version

_No need_
