### ISSUE TITLE
Dark Reader on Gmail

### ISSUE THREAD

**Issue by ballII** [darkreader/darkreader#1116]
The dynamic mode renders Gmail best with the Gmail's Dark theme, but the dynamic mode significantly slows down the browser. The Filter mode (with Gmail's default theme) is quicker and fine except that the unread email titles in the inbox are not obvious enough to distinguish themselves from the read ones. I suppose the Static mode allows users to customize the CSS code? However, I am not a coder and cannot find an example code online to change the look of the *unread* email titles. Can anyone here kindly offer some tips? Thank you.

**Comment by oxguy3** [comment]
This doesn't directly answer your issue, but you might consider disabling Dark Reader on mail.google.com and instead using Gmail's built-in dark theme (click the cog icon, go to Themes, scroll down to Dark). Their dark theme is very clean and doesn't have any visual hierarchy issues like the one you've described.

The one thing I don't like about Gmail's dark theme is that it doesn't apply to the loading screen. I use some custom CSS to fix this; you can install the following stylesheet with [Stylus](https://add0n.com/stylus.html) or Stylish:
```css
@-moz-document domain("mail.google.com") {
#loading {
    background-color: #111;
}
#loading,
#loading .msg,
#loading .msgb {
    color: #bbb;
}
#loading a,
#loading .submit_as_link {
    color: #66f;
}
}
```
