### ISSUE TITLE
Default image viewer and pdf viewer probably shouldn't be effected by default

### ISSUE THREAD

**Issue by Kommynct** [darkreader/darkreader#114]
Well, the issue with pdf's is just the interface, so, maybe that can be fixed with the dev tools.

Same with image viewer.

**Comment by alexanderby** [comment]
PDF viewer is an all-in-one element, I will try to experiment with SVG filter regions to make it invert page area only.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
