### ISSUE TITLE
[Broken Website] bing chat and bing.com

### ISSUE THREAD

**Issue by dudasa** [darkreader/darkreader#11496]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

bing chat have large white strips on top and bottop. bing.com have white strip on the tilte of the top article

### Website Address

https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx

### Steps To Reproduce

just visit the website 

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/25896171/8f18ef69-e606-41f7-85df-bb795ebc9e7c)
![image](https://github.com/darkreader/darkreader/assets/25896171/792444ca-9696-45ec-8888-d3209b3230da)

### Operating System

Windows 11 Home 22H2 22621.1848

### Web Browser name and version

Edge Version 114.0.1823.67 (Official build) (64-bit)

### Dark Reader version

4.9.64

**Comment by dudasa** [comment]
also the bing chat window is white
![image](https://github.com/darkreader/darkreader/assets/25896171/be79f22d-1cfb-425d-ad94-7f06aac06071)

**Comment by cigaryno** [comment]
This also occurs to me when the Bing AI answers something I typed in the search box.

**Comment by Dreamer8** [comment]
Confirmed, Edge, Dark Reader, Windows 10, latest versions.

First, Dark Reader didn't work at all at bing.com, later it was working good, but it's broken now, I have the same results as on the screenshots above.

BTW Reply to my question, why dark mode is not supported from bing:

> "Bing does support dark mode, but it is not yet available for all users."

Anyway, I tried it and for me dark mode IS available already!

Here is the link, how to enable it:

https://www.makeuseof.com/bing-chat-enable-dark-mode/

I just had to refresh page, because it was broken / white after I changed it and disabled Dark Reader.

**Comment by liar666** [comment]
Happens under FF/Linux too.
Also very weird: activating DR , then deactivating DR, does not result in recovering original colors...
- Initial colors
![screenshot_2023-08-17-21 49](https://github.com/darkreader/darkreader/assets/3216927/40e2b4e7-be08-43b6-a23f-bf5238427553)
- Activation of DR
![screenshot_2023-08-17-21 50](https://github.com/darkreader/darkreader/assets/3216927/b58af0e4-db31-4b3c-a981-4622500fe7c5)
- De-activation of DR
![screenshot_2023-08-17-21 50_000](https://github.com/darkreader/darkreader/assets/3216927/dc46ea9a-36d8-444b-989c-0569ea9875d7)

**Comment by Kyzoku** [comment]
I wish my bing looked that good.

![BING](https://github.com/darkreader/darkreader/assets/49911814/2e133f22-d6d9-4efa-8133-3868b5bbd487)

**Comment by Dreamer8** [comment]
@liar666
@Kyzoku

Please read my post above, Bing chat supports dark mode for all users now (confirmed by Bing AI), just enable it, disable Dark Reader for Bing and refresh page.

Tested with Edge, Windows 10.

**Comment by menawi** [comment]
@dudasa 

- I found a workaround that seems to work for me so far.

```css
================================

bing.com

/*DO NOT DELETE THE EXISTING CSS STYLING FROM DARK READER. 
JUST ADD THE FOLLOWING STYLING AFTER IT */

div.main {
filter: invert(1);
}
.entity-image-button{
filter: initial;
}
.main-container{
filter: invert(1);
}
.container{
filter: invert(1);
}
div.content.text-message-content {
filter: initial !important;
  background-color: #a55b00;
}
cib-see-more-container{
filter: invert(1) ; 
}

``` 

- Make sure to restart your browser and then check if the styling is still applied.
![Screenshot 2023-08-18 at 20 05 51](https://github.com/darkreader/darkreader/assets/105254409/716750f8-f416-4285-9c11-e300e2e49f1c)
![Screenshot 2023-08-18 at 20 07 05](https://github.com/darkreader/darkreader/assets/105254409/fd3af611-5611-4de3-889d-8f715dec6a09)
