### ISSUE TITLE
[Broken Website] Claude.AI

### ISSUE THREAD

**Issue by scowalt** [darkreader/darkreader#11520]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Header and site logo are messed up

### Website Address

https://claude.ai/

### Steps To Reproduce

1. Navigate to https://claude.ai/
2. Sign in with Google
3. Start a chat
4. Observe

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/1100550/aeb3eaea-912e-422e-bfa7-012e54398a26)
![image](https://github.com/darkreader/darkreader/assets/1100550/a1a074e4-c637-4d04-8215-94b1dc761273)

### Operating System

Windows

### Web Browser name and version

Chrome 114

### Dark Reader version

4.9.64

**Comment by zychen20** [comment]
I think you might have forgotten to search closed issues, my fix #11506 was merged but it seems still not pushed to production yet. You can copy the codes and apply in "Dev tools" first.

**Comment by attila-kun** [comment]
My latest styles for Claude:

```css
================================

claude.ai

INVERT
img[src="/anthropic_app_icon.png"]

CSS
.bg-gradient-to-b {
    background-image: linear-gradient(to bottom, hsl(var(--darkreader-neutral-background)/1), hsl(var(--darkreader-neutral-background)/0)) !important;
}
.dsfXeN,
.dsfXeN::before {
    background: black;
}
.dBmDVz {
    box-shadow: none !important;
}
.eUopBN {
    background-image: none !important;
}

================================
```
