### ISSUE TITLE
[Broken Website] Microsoft Edge PDF Viewer

### ISSUE THREAD

**Issue by x1ly4x** [darkreader/darkreader#11792]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The Dark Reader doesn't work well on the named site. See screenshot.

### Website Address

none

### Steps To Reproduce

none

### Screenshots

![Screenshot 2023-10-06 193147](https://github.com/darkreader/darkreader/assets/88503351/98e58c61-bffe-44c1-8e20-985f2aa5f809)

### Operating System

Windows

### Web Browser name and version

Microsofrt Edge

### Dark Reader version

latest

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
