### ISSUE TITLE
White `All activity` section at Github.com

### ISSUE THREAD

**Issue by mikhaelkh** [darkreader/darkreader#1195]
When you logged in, at https://github.com `All activity` section is white and barely readable with default settings.

**Comment by spikespaz** [comment]
Same issue
![image](https://user-images.githubusercontent.com/12502988/55312207-c3f46480-5419-11e9-87b7-50e0fba3e6d0.png)

**Comment by spikespaz** [comment]
This is caused by the very popular Refined GitHub extension: https://github.com/sindresorhus/refined-github

This should be a priority issue because a lot of people use the extension. Not just speaking for myself, I'm sure.

**Comment by mikhaelkh** [comment]
Yes, [Refined GitHub](https://github.com/sindresorhus/refined-github) is needed. It injects some stylesheets, I think this one is messing with Dark Reader's:
```css
.dashboard .js-all-activity-header + div {
    background-color: rgb(255, 255, 255);
    margin-top: 8px !important;
    border-width: 1px;
    border-style: solid;
    border-color: rgb(209, 213, 218);
    border-image: initial;
    border-radius: 3px;
}
```
