### ISSUE TITLE
[Broken Website] Bright background not adjusted in various Asciidoctor Docs content blocks

### ISSUE THREAD

**Issue by stanio** [darkreader/darkreader#12369]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The bright background of various content (info/tip, code) blocks on the Asciidoctor Docs site doesn't get adjusted for a dark appearance.

### Website Address

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

### Steps To Reproduce

1. Open the referenced site/page with Dark Reader enabled;
2. Observe the result colors.

### Screenshots

![asciidoc-quick-reference](https://github.com/darkreader/darkreader/assets/1247730/eef512fa-82ed-4321-9a69-d69693743339)

The same is observed with certain inline phrasing content, also:

![asciidoctor-docs](https://github.com/darkreader/darkreader/assets/1247730/8f6b034c-dd32-463f-9a7f-51c18477afc4)

### Operating System

Windows 10

### Web Browser name and version

Firefox 124.0b3, Edge 122.0.2365.52

### Dark Reader version

4.9.77

### Additional Context

I'm only speculating it is related to site rules like:

```css
.doc .admonitionblock td.content {
  background:#fafafa;
  background:var(--admonition-background);
  ...
}

.doc .listingblock pre:not(.highlight),
.doc .literalblock pre,
.doc pre>code {
  background:#fafafa;
  background:var(--pre-background);
  ...
}

.doc .colist>table code,
.doc p code,
.doc thead code {
  background:#fafafa;
  background:var(--code-background);
  ...
}
```

Dark Reader doesn't appear to handle background colors specified using the CSS `background` shorthand property.
