### ISSUE TITLE
[Bug] Developer Tools don't apply after browser restart

### ISSUE THREAD

**Issue by Szuruburu** [darkreader/darkreader#12593]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Each time I open browser my custom rules for...

```css
================================

onedrive.live.com

CSS
* {
    border: none !important;
}

================================
```
and
```css
================================

outlook.live.com
hotmail.com

CSS
* {
    border: none !important;
}
.ms-Checkbox {
    background-color: #262A2B !important;
}

================================
```

...don't apply. I have to go to Developer Tools and hit "Apply". They're there, they just won't apply on browser start.
I copy the entire thing from another computer. Is this maybe an issue?

### Website Address

onedrive.live.com, outlook.live.com, hotmail.com

### Steps To Reproduce

1. Make edits as in the above description
2. Copy all of the "Dark Reader developer tools" code to another OS
3. Start browser, hit apply
4. Restart browser - the changes are not applied

### Expected Behavior

When I copy the code from another OS/computer it should apply automatically when I start the browser.

### Actual Behavior

The changes I made on another machine are not automatically applied on the one I copied them to.

### Operating System

Windows 10/Windows 11/Linux

### Web Browser name and version

Google Chrome 123.0.6312.107

### Dark Reader version

4.9.82
