### ISSUE TITLE
[Broken Website] YouTube comment boxes

### ISSUE THREAD

**Issue by Hulayki** [darkreader/darkreader#12725]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The comment boxes are grey on YouTube

### Website Address

https://www.youtube.com

### Steps To Reproduce

1. Find a video or post on YouTube
2. See the problem

### Screenshots

![Screenshot 2024-05-15 180104](https://github.com/darkreader/darkreader/assets/97475801/6db52ad2-ac0f-4b2c-a471-e3e8320a12af)

### Operating System

Windows 11

### Web Browser name and version

Chrome 124

### Dark Reader version

4.9.85

**Comment by oberrich** [comment]
The color is coming from here:
![image](https://github.com/darkreader/darkreader/assets/6305520/2b5bc815-ae97-4ac3-82dc-08fa49bc3740)

**Comment by Hulayki** [comment]
@oberrich 
Thank you so much! 💗

And can you do something with this?

![Screenshot 2024-05-15 211919](https://github.com/darkreader/darkreader/assets/97475801/291d674b-7401-49d0-a887-b0b2e09163f1)

**Comment by oberrich** [comment]
> @oberrich Thank you so much! 💗
> 
> And can you do something with this?
> 
> ![Screenshot 2024-05-15 211919](https://private-user-images.githubusercontent.com/97475801/330934019-291d674b-7401-49d0-a887-b0b2e09163f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDE2MzcsIm5iZiI6MTcxNTgwMTMzNywicGF0aCI6Ii85NzQ3NTgwMS8zMzA5MzQwMTktMjkxZDY3NGItNzQwMS00OWQwLWE4ODctYjBiMmUwOTE2M2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE5Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDRiZTc5ZjZjYzdiZmQ2YTA5ZTBhN2ZhMjdiYjQ0MDViY2U5MDUwMTU5MmJhMWRkZDFkYTc3NzhkZGMyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZT7_ux-ZG6oWox4oCIDqFj0bDevYFp2RbZ3KieLmEV0)

```CSS
.tp-yt-paper-menu-button {
    background: none !important;
}
```

**Comment by oberrich** [comment]
And if you want to get rid of 6px wide borders in details box:

```CSS
ytd-horizontal-card-list-renderer.ytd-structured-description-content-renderer:not(:first-child), ytd-metadata-row-container-renderer.ytd-structured-description-content-renderer:not(:first-child), ytd-structured-description-content-renderer[inline-structured-description] ytd-horizontal-card-list-renderer.ytd-structured-description-content-renderer, ytd-structured-description-content-renderer[inline-structured-description] ytd-error-corrections-section-renderer.ytd-structured-description-content-renderer, ytd-structured-description-content-renderer[inline-structured-description] ytd-video-description-infocards-section-renderer.ytd-structured-description-content-renderer {
  border-top-width: 1px !important;
}
```
