### ISSUE TITLE
[Feature Request] Don't invert pdf UI

### ISSUE THREAD

**Issue by tom-huntington** [darkreader/darkreader#12793]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Chrome's pdf UI already matches the system's colour.

When I use dark mode, the already dark UI gets inverted and flash bangs me.

Would be nice if I didn't have to use an electron app https://github.com/Lunarequest/NightPDF which breaks my chrome keybindings when open.

### Screenshots

![Screenshot 2024-06-03 165506](https://github.com/darkreader/darkreader/assets/55266932/8bcf18d8-c297-44c2-bff4-3540ab538756)

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
