### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by tjk918** [darkreader/darkreader#13242]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Some elements are broken on this site. I am currently fixing a portion of this using a userscript with the following css:
```css
  .page_charts_section_charts_item_details_average_num { background: var(--average-rating); -webkit-background-clip: text; }
  .page_home_intro_content_text_sitename,
  .disco_avg_rating { background-clip: text !important; }
  #column_container_right *,
  .disco_expand_section_btn { background: #111 !important; }
  #ui_search_input_main_search { background: #252525; }
  .page_home_section_featured_content_content_item .page_section_dynamic_fade_cover { background: linear-gradient(to bottom,rgba(128,128,128,0),#212121); }
  .ui_button { background: 444 !important; }
```

Pretty ugly css i know but it gets the job done for some of the site anyways
(PS they also recently changed the main charts page so some of that probably isnt necessary anymore)

### Website Address

rateyourmusic.com

### Steps To Reproduce

Album/song/etc scores are not shown because the text is displayed as a gradient with a background clip that dark reader ignores eg. [https://rateyourmusic.com/artist/radiohead](https://rateyourmusic.com/artist/radiohead)
The sidebar and lots of buttons also are white still

### Screenshots

![image](https://github.com/user-attachments/assets/ce866113-7655-4bec-9306-b9c87e950822)

### Operating System

Linux

### Web Browser name and version

Firefox 127.0 & chrome etc

### Dark Reader version

latest
