### ISSUE TITLE
[Broken Website] creativecommons.org

### ISSUE THREAD

**Issue by alkaris2** [darkreader/darkreader#13284]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When Dark Reader is enabled for [Creativecommons.org](https://Creativecommons.org) it doesn't quite display things correctly, mainly how the text is colored which creates this weird color contrasting effect because it's applying a `text-shadow` or text outline showing over backgrounds of links.

This applies to every other theme style that you can select within Dark Reader. You just need to remove the following for Creativecommons.org;

```CSS
main a {
background: linear-gradient(var(--darkreader-bg--underline-color),var(--darkreader-bg--underline-color)),linear-gradient(var(--darkreader-bg--underline-color),var(--darkreader-bg--underline-color)),linear-gradient(currentColor,currentColor);
}
```

also the other line under `main a` doesn't appear to do or change anything and should be removed for creativecommons.org.

```CSS
main a {
text-decoration-color: currentcolor;
}
```

### Website Address

https://creativecommons.org

### Steps To Reproduce

1. Visit Creativecommons.org
2. Enable Dark Reader

### Screenshots

![Light Mode](https://github.com/user-attachments/assets/7ea73f16-4e3a-4d51-a700-37b684a0625c)

![Dark Mode](https://github.com/user-attachments/assets/062ac7d4-29cf-4b80-ba15-ba0276a13446)

### Operating System

Manjaro Linux 24.0.7

### Web Browser name and version

Firefox 130.0 (64-bit)

### Dark Reader version

Version 4.9.92
