### ISSUE TITLE
[Broken Website] foundation.rust-lang.org headshot size

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#13392]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark reader makes
```css
.peoplelist li {
  background: var(--darkreader-bg--lightgray);
}
```
which overrides site styles
```css
.peoplelist li {
...
  background-size: cover;
  background-position: center;
...
}
```

### Website Address

https://foundation.rust-lang.org/about/

### Steps To Reproduce

1. Open https://foundation.rust-lang.org/about/
2. Filter, dark settings in Dark reader

### Screenshots

<details>
<summary>Broken</summary>

![image](https://github.com/user-attachments/assets/cc208e35-af78-4c55-91f6-c564951a096d)

</details>

<details>
<summary>With site exception</summary>

![image](https://github.com/user-attachments/assets/4e6605a5-5bc8-4185-a175-0c2ab99aa6c4)

</details>

### Operating System

Fedora 40

### Web Browser name and version

Firefox 131

### Dark Reader version

4.9.94
