### ISSUE TITLE
Unable to interact with check boxes on Protonmail

### ISSUE THREAD

**Issue by geeknik** [darkreader/darkreader#1384]
While using Firefox 68 + DarkReader 4.7.12, I'm unable to toggle check boxes on Protonmail. Instead of selecting the item like normally, it just acts like a click and opens the email. I'm also unable to star any emails.

![Screenshot_2019-06-18 (17) Inbox geeknik protonmail ch ProtonMail](https://user-images.githubusercontent.com/466878/59704153-16475500-91c1-11e9-8431-0ff574c6cbf9.png)

**Comment by geeknik** [comment]
I reset the Protonmail theme to defaults under Settings->Appearance and it fixed the interaction issue.

**Comment by ShalokShalom** [comment]
I have tried this too and mine are still locking not very smooth. 
Same as in your screenshot. 
Text reads fine now, thanks.

**Comment by mikerouxfr** [comment]
Same issue even after using the reset to default trick.

I guess it is because **DarkReader** use `background-color` instead of `background` in the injected inline CSS.

-----

Here is the custom set rule I used to fix the issue:
```css
================================

mail.protonmail.com

CSS
.customCheckbox-input + .customCheckbox-mask {
    background: #262829;
}
```

Click your **DarkReader** shortcut and find the `🛠 Dev Tools` (name may differ in other locales; Then, insert the rule somewhere in the file (below beta.protonmail.com for example).
