### ISSUE TITLE
[Bug] Chrome extension component styles affected

### ISSUE THREAD

**Issue by adamlui** [darkreader/darkreader#13973]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [x] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [x] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Here https://github.com/adamlui/ai-web-extensions/issues/141#issuecomment-2686493792 a user of my extension reported Dark Reader in Mac Chrome darkens Chrome extension toolbar icon popup menus to the point of unusability (I wasn't able to reproduce in Win Chrome though)

### Website Address

https://chatgptwidescreen.com

### Steps To Reproduce

1. Install https://chrome.chatgptwidescreen.com on a Mac
2. Pin icon to toolbar
3. Click it
4. Observe toggles become obscured

### Expected Behavior

No scheme hack of extension components like in Win Chrome

### Actual Behavior

Mac Chrome extension components are re-stylized

### Screenshots

Mac Chrome:

![Image](https://github.com/user-attachments/assets/03019575-03b5-4f0c-b60f-302d45040063)

Win Chrome (133.0.6943.142) using Dark Reader 4.9.103:

<img width=255 src="https://github.com/user-attachments/assets/2477dadf-4269-42dc-b5d7-ab61e1a1548a">

### Operating System

Mac

### Web Browser name and version

Chrome

### Dark Reader version

15.4

### Additional Context

I don't own a Mac but @happyf-weallareeuropean can reveal what Chrome version

**Comment by alexanderby** [comment]
The extension cannot have access to other's extension popup window, unless there is a security issue in Chrome. If you are injecting the popup into web content, try using a closed shadow DOM node. Maybe the user is using some system-wide dark mode tool or "Auto Dark Mode for Web Contents" in `chrome://flags`. The system-wide dark color scheme shouldn't be an issue, but maybe you have some dark mode media queries in your style sheets.

**Comment by adamlui** [comment]
Here's the short stylesheet check it out:

```css
/* General */
html { height: fit-content ; min-height: 89px }
body {
    width: max-content ; margin: 0 ; font-size: .905rem ;
    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto,
        "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", sans-serif    
}

/* Color/fade mods */
.highlight-on-hover:hover { background: rgb(100,149,237) }
.disabled { opacity: 0.3 ; pointer-events: none }

/* Loader */
.loading-bg {
    background-color: white ; width: 100% ; height: 100% ; position: absolute ; z-index: 1111 ;
    display: inline-grid ; align-content: center ; justify-content: center /* center spinner */
}
.loading-spinner {
    width: 19px ; aspect-ratio: 1 ; border-radius: 50% ; border: 3px solid #000 ;
    animation: loader-move-head-tail 0.8s infinite linear alternate, loader-rotate 1.6s infinite linear
}
@keyframes loader-move-head-tail {
     0% { clip-path: polygon(50% 50%, 0 0, 50% 0, 50% 0, 50% 0, 50% 0, 50% 0) }
     12.5% { clip-path: polygon(50% 50%, 0 0, 50% 0, 100% 0, 100% 0, 100% 0, 100% 0) }
     25% { clip-path: polygon(50% 50%, 0 0, 50% 0, 100% 0, 100% 100%, 100% 100%, 100% 100%) }
     50% { clip-path: polygon(50% 50%, 0 0, 50% 0, 100% 0, 100% 100%, 50% 100%, 0 100%) }
     62.5% { clip-path: polygon(50% 50%, 100% 0, 100% 0%, 100% 0, 100% 100%, 50% 100%, 0 100%) }
     75% { clip-path: polygon(50% 50%, 100% 100%, 100% 100%, 100% 100%, 100% 100%, 50% 100%, 0 100%) }
     100% { clip-path: polygon(50% 50%, 50% 100%, 50% 100%, 50% 100%, 50% 100%, 50% 100%, 0 100%) }
}
@keyframes loader-rotate { 
    0% { transform: scaleY(1) rotate(0deg) } 49.99% { transform: scaleY(1) rotate(135deg) }
    50% { transform: scaleY(-1) rotate(0deg) } 100% { transform: scaleY(-1) rotate(-135deg) }
}

/* Header */
.menu-header {
    border-bottom: solid 1px lightgrey ; padding: 5px 5px 5px 0 ; margin: 0 ;
    min-height: 38px ; display: flex; background: white ; align-items: center }
.logo { margin: 4px 8px 4px 12px ; position: relative ; top: 3px }
.menu-title { font-size: 0.85rem ; font-weight: 600 ; padding-right: 3px }
.master-toggle { margin-left: auto ; display: flex }

/* Menu item elements */
.menu-entry {
    position: relative ; align-items: center ; border-bottom: 1px solid lightgrey ;
    display: flex ; min-height: 2rem ; padding: 0 14px 0 2px ; white-space: nowrap ; font-size: 91%
}
.menu-icon { padding: 8px }
.menu-entry:hover span:not(.track), .menu-entry:hover .caret { filter: invert(1) } /* invert setting labels on hover */
.menu-entry > label > .track { transform: scale(0.95) ; top: 1px } /* make child toggles smaller */
.menu-prompt { margin-left: 2px } /* align non-toggle items */

/* Toggle elements */
.toggle .track {
    display: block ; border-radius: 7px ; position: relative ; transform: scale(0.95) ; background: white ; 
    border: 1px solid black ; top: 1px ; height: 10px ; width: 18px ; transition: background 0.08s ease-in-out
}
.toggle.on .track { background: black ; transition: background 0.15s ease-in-out }
.toggle .track::before { /* knob */
    content: "" ; position: absolute ; height: 0.625rem ; width: 0.625rem ; left: -0.04rem ; top: -0.05rem ;
    border: 1px solid black ; border-radius: 50% ; background: white ; transition: transform 0.08s ease-in-out
}
.toggle.on .track::before { transform: translateX(9px) ; transition: transform 0.15s ease-in-out }
  
/* Footer */
footer {
    font-size: 12px ; text-align: center ; color: #999 ; background: #f5f5f5 ; height: 40px ; line-height: 40px }
footer > .menu-icon { position: absolute ; bottom: -10px ; opacity: 0.7 }
.cjs-span { position: absolute ; bottom: -.25rem ; left: 0.7rem }
.cjs-span img { opacity: 0.5 } .cjs-span:hover img { opacity: 1 ; transition: 0.25s }

/* Non-baseline features */
@supports (overflow: clip) { body { overflow: clip }}
@supports (user-select: none) { body, button, input, select, textarea { user-select: none }}
@supports (cursor: pointer) { .highlight-on-hover:hover, .toggle .track, .cjs-span { cursor: pointer }}
```

No special queries, also he said "seems Reader will turn it to Dark now, after i update to 15.4." but there is no such version scheme is there? Unless he typo'd in which case sounds like he's saying Dark Reader update turned popup inverted style
