### ISSUE TITLE
[Bug] `IGNORE IMAGE ANALYSIS` doesn't stop color inversion of SVG background images

### ISSUE THREAD

**Issue by lumynou5** [darkreader/darkreader#14102]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [x] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [x] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Dark Reader inverts SVG background images with `stroke` assigned to white, even if the fix asks not to analyze the images.

### Website Address

https://www.gamer.com.tw/

### Steps To Reproduce

1. Add the following dynamic theme fix
   ```
   IGNORE IMAGE ANALYSIS
   .sidenav__icon
   ```
2. Visit the website.
3. See the down arrow icon in the left side navigation column is still inverted.

### Expected Behavior

Dark Reader should leave the background images as-is instead of replacing with inverted one.

### Actual Behavior

The background images are inverted.

```css
.service__icon.icon-arrow {
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiPjxkZWZzPjxmaWx0ZXIgaWQ9ImRhcmtyZWFkZXItaW1hZ2UtZmlsdGVyIj48ZmVDb2xvck1hdHJpeCB0eXBlPSJtYXRyaXgiIHZhbHVlcz0iMC4yNDkgLTAuNjE0IC0wLjY3MiAwLjAwMCAxLjAzNSAtMC42NDYgMC4yODggLTAuNjY0IDAuMDAwIDEuMDIwIC0wLjYzNiAtMC42MDkgMC4yNTAgMC4wMDAgMC45OTQgMC4wMDAgMC4wMDAgMC4wMDAgMS4wMDAgMC4wMDAiIC8+PC9maWx0ZXI+PC9kZWZzPjxpbWFnZSB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbHRlcj0idXJsKCNkYXJrcmVhZGVyLWltYWdlLWZpbHRlcikiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjNhV1IwYUQwaU1qUWlJR2hsYVdkb2REMGlNalFpSUhacFpYZENiM2c5SWpBZ01DQXlOQ0F5TkNJZ1ptbHNiRDBpYm05dVpTSWdlRzFzYm5NOUltaDBkSEE2THk5M2QzY3Vkek11YjNKbkx6SXdNREF2YzNabklqNEtQSEJoZEdnZ1pEMGlUVFVnT0M0MU5rd3hNaUF4TlV3eE9TQTRMalUySWlCemRISnZhMlU5SWlNME5qUTJORFlpSUhOMGNtOXJaUzEzYVdSMGFEMGlNaUlnYzNSeWIydGxMV3hwYm1WallYQTlJbkp2ZFc1a0lpQnpkSEp2YTJVdGJHbHVaV3B2YVc0OUluSnZkVzVrSWk4K0Nqd3ZjM1puUGdvPSIgLz48L3N2Zz4=");
}
```

### Screenshots

![Image](https://github.com/user-attachments/assets/88afe8c5-1dc7-4fdc-a0d6-326514de282e)

### Operating System

Arch Linux

### Web Browser name and version

Firefox 136.0

### Dark Reader version

4.9.103

### Additional Context

I was trying to fix the dynamic theme by using `INVERT` on the icons, but the down arrow is inverted twice, resulting an invisible black icon.
