### ISSUE TITLE
[Broken Website] `zenn.dev` White background

### ISSUE THREAD

**Issue by akku1139** [darkreader/darkreader#14196]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Sometimes the background for `zenn.dev` becomes white.
The attached screenshot is from the home page, but this issue can also occur on other pages.

### Website Address

https://zenn.dev/

### Steps To Reproduce

1. Install Dark Reader
2. Open `zenn.dev`

### Screenshots

![Image](https://github.com/user-attachments/assets/42d3aa95-a4ad-4fbb-9135-48ec072b0e82)

### Operating System

Arch Linux

### Web Browser name and version

Firefox Developer Edition for Arch Linux 138.0b1 (64-bit)

### Dark Reader version

4.9.103

### Additional Context

A similar pull request: https://github.com/darkreader/darkreader/pull/4133

I am using the following custom CSS to avoid this issue:
```css
:root {
  /* --c-bg-base: unset !important; */
  --c-bg-base: #0a0c0c !important;
  /* --c-bg-primary-lighter: unset !important; */
  --c-bg-primary-lighter: #0e1112 !important;
  --c-bg-neutral: var(--darkreader-bg--c-bg-neutral) !important;
}
```

**Comment by Myshor** [comment]
I could not reproduce so it's hard to fix it but

As you added your custom CSS fix I could use it but it still needs some changes:
- `  --c-bg-base: #0a0c0c !important;` that static color must be changed into something that will be different when light scheming is enabled in Dark Reader. As I checked what is used when everything is loaded OK on my side then `  --c-bg-base: var(--darkreader-bg--c-bg-base) !important;` could be nice to use
- same with `  --c-bg-primary-lighter: #0e1112 !important;` => I can see there is something like this used by Dark Reader: `  --c-bg-primary-lighter: var(--darkreader-bg--c-bg-primary-lighter) !important`

Can you at least check if that variables fixes the problem for you?

**Comment by akku1139** [comment]
Your proposed variables work well.
Additionally, the following CSS is required to fix some of the issues that have been discovered:

```css
:root {
  --c-bg-base: var(--darkreader-bg--c-bg-base) !important;
  --c-bg-primary-lighter: var(--darkreader-bg--c-bg-primary-lighter) !important;
  --c-bg-neutral: var(--darkreader-bg--c-bg-neutral) !important;
  --c-bg-emoji: var(--darkreader-bg--c-bg-base);
}
```
