### ISSUE TITLE
[Feature Request] Transparency as an Option

### ISSUE THREAD

**Issue by aliyss** [darkreader/darkreader#14199]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Using the ``dynamic theme`` and adding following rules just above IGNORE INLINE STYLE:

```css
:root {
    --darkreader-background-25292e: transparent !important;
    --darkreader-background-f1f3f4: transparent !important;
    --darkreader-background-f2f2f2: transparent !important;
    --darkreader-background-f6f8fa: transparent !important;
    --darkreader-background-ffffff: transparent !important;
}
```

I can get following output:

![Image](https://github.com/user-attachments/assets/23b07265-337b-4cbd-9440-5c07a82402ce)

I am now wondering if it would make sense to add this feature directly to darkreader. This would be especially useful for popups and stuff like that where one would have to add a backdrop-filter: blur(10px) or similar to actually have it working as intended.

I am very willing to help out. So if I could get a hint on which files to edit that affect the logic on how the background is calculated that would be great.
