### ISSUE TITLE
[Broken Website] Missing elements on California Legislative Information

### ISSUE THREAD

**Issue by hkamran80** [darkreader/darkreader#14425]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Many elements of the site, like bill navigation, login, quick search, and more, completely disappear and are unusable when Dark Reader is active. The root cause seems to be `display: none` being set through an inline stylesheet that is added whenever Dark Reader is active, regardless of the theme:

```css
// ...
#quick_search {display: none;}
#tab_panel {display: none;}
#system {display: none;}
#quick_search {display: none;}
#navigation {display:none;}
#breadcrumbs {display:none;}
#bill_version {display:none;}
#social_network {display:none;}
#title_bill_search {display:none;}
// ...
```

### Website Address

leginfo.legislature.ca.gov

### Steps To Reproduce

1. Install Dark Reader
2. Visit any bill on the legislature's website
3. Notice the missing elements and lack of functionality when Dark Reader is active

### Screenshots

Fresh browser (enacted bill):

<img width="1624" alt="Fresh Browser - Enacted Bill (AB 375)" src="https://github.com/user-attachments/assets/edcbd949-a289-4418-8c77-ec24159bb683" />

Fresh browser (new bill):

<img width="1624" alt="Fresh Browser - New Bill (AB 16)" src="https://github.com/user-attachments/assets/6139c759-6e7e-48a1-8a34-dcf7108a3208" />

Dark Reader (enabled, enacted bill):

<img width="1624" alt="Dark Reader (Active) - Enacted Bill (AB 375)" src="https://github.com/user-attachments/assets/e98cd067-0f05-43d9-9120-5974420f035f" />

Dark Reader (enabled, new bill):

<img width="1624" alt="Dark Reader (Active) - New Bill (AB 16)" src="https://github.com/user-attachments/assets/6c49ef12-4fc1-4567-b498-7c655c6e7a33" />

Dark Reader (disabled, enacted bill):

<img width="1624" alt="Dark Reader (Inactive) - Enacted Bill (AB 375)" src="https://github.com/user-attachments/assets/feba181c-6070-49db-89c7-2d0c21c11b21" />

Dark Reader (disabled, new bill):

<img width="1624" alt="Dark Reader (Inactive) - New Bill (AB 16)" src="https://github.com/user-attachments/assets/399d8268-04d8-4303-bc0b-a46c7e4b301c" />

### Operating System

macOS Sonoma 14.4

### Web Browser name and version

Firefox 140.0.2

### Dark Reader version

4.9.106
