### ISSUE TITLE
#buyerComments on Ebay looks a little funny in Dynamic Mode

### ISSUE THREAD

**Issue by spikespaz** [darkreader/darkreader#1442]
The text is darker than it should be, as such:

![image](https://user-images.githubusercontent.com/12502988/61495540-2001db00-a96e-11e9-8d84-4521c1a8ca78.png)

Here's the modified section in the DevTools:

```css
================================

www.ebay.*
www.ebay.*.*

CSS
html, body {
    background-image: none !important;
}
#buyerComments {
 color: ${rgba(0, 0, 0, 0.8)} !important;
}

================================
```

Here's what it looks like now:
![image](https://user-images.githubusercontent.com/12502988/61495468-f5b01d80-a96d-11e9-9cf1-bc74411a8664.png)
