### ISSUE TITLE
[Feature Request] Dark Loading Screen

### ISSUE THREAD

**Issue by hakaneroztekin** [darkreader/darkreader#1519]
Dark reader is awesome especially at night, but when you open a new tab (Ctrl+T), the loading screen for the tab is pure white that is the Firefox default and it is annoying. If it is possible to make loading screen of new tabs dark too, it would be awesome.

**Comment by privacyguy123** [comment]
+1 on this - my poor retinas. I can't get the custom CSS to understand about:newtab.

**Comment by privacyguy123** [comment]
Bump.

**Comment by Polyterative** [comment]
That does not depend on dark reader I think. On chrome the same issue is solved by changing the browser's theme

**Comment by privacyguy123** [comment]
I'm already using FireFox built in Dark Theme - pretty sure this is reader specific.

**Comment by inthreedee** [comment]
What you're seeing is just Firefox's default background canvas and changing the theme doesn't solve it.  I don't think addons have access to change this for security reasons, so there's probably nothing Dark Reader can do.

Shadowfox applies a userChrome.css change that mostly, but not completely, fixes it.  This is how they do it:
https://github.com/overdodactyl/ShadowFox/blob/master/css/userChrome-files/remove_white_flash.css

You could take that code, replace `var(--in-content-page-background)` with an actual color (ie.  `#2d2d2d`), and put it in a `[profile]/chrome/userChrome.css` file.  In Firefox 69, userChrome.css files aren't read by default as part of their security improvements.  You can enable it in about:config.

**Comment by jpuris** [comment]
Until dark reader is able to do this, I've settled on https://github.com/overdodactyl/ShadowFox to solve this issue.

**Comment by joelostblom** [comment]
Put the following in `userChrome.css` in your default profile:

```css
.browserContainer {
    background-color: #3d3d3d !important;
}
```

and the below in `userContent.css` in the same folder:

```css
@-moz-document url("about:blank") {
	html {
	  background-color: #3d3d3d;
	}
}

@-moz-document url(about:newtab) {
	body, #newtab-customize-overlay {
       background-color: #3d3d3d !important;
       color: rgb(166,166,166) !important;
    }
}
```

This worked for me while using `about:blank` as my new tab page. Removes both the flash and restyles the page background in the new tab.
