### ISSUE TITLE
Doesn't apply to PDF files opened on firefox

### ISSUE THREAD

**Issue by underlineGalaxy** [darkreader/darkreader#1541]
So if I open a PDF file (a guess that it can also apply to txt or word documents) it doesn't dark the whites, it would be a cool feature to have.

Altough that got me thinking... if there exists an open source program that is like dark reader but for these kind of files, it's just a matter of implementation (and if anyone has found one like that or maybe a plugin link it to me because I would like to download it)

**Comment by krupenja** [comment]
Duplicate of #374

**Comment by dn7** [comment]
Workaround (one click per PDF):
create a new bookmark (bookmarklet) with the following Location (target):
`javascript:void(viewer.style = 'filter: grayscale(0%) invert(100%) contrast(100%) brightness(100%)')`

Per https://github.com/darkreader/darkreader/issues/374#issuecomment-640622375
Thanks to @ak0005

**Comment by Gusted** [comment]
Firefox won't allow us to access pdf pages.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
