### ISSUE TITLE
Not work in online PDF page in Chrome in dynamic mode

### ISSUE THREAD

**Issue by luo-chuan** [darkreader/darkreader#1730]
For the same online pdf page in Chrome, the plugin "Midnight Lizard" can invert the page's color, but "Dark Reader" can't.  
![darkreaderdynamic](https://user-images.githubusercontent.com/33930736/68875202-60673f00-073d-11ea-91e2-19f1df000420.jpg)  
![midnightlizard](https://user-images.githubusercontent.com/33930736/68875175-56454080-073d-11ea-8795-0f727ff67502.jpg)

**Comment by krupenja** [comment]
Duplicate of #374

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
