### ISSUE TITLE
Invert colors for PDF files

### ISSUE THREAD

**Issue by Matt-Gleich** [darkreader/darkreader#1774]
Every day I need to view a lot of PDF files in chrome and I was wondering if Dark Reader could invert the colors of the PDF so it can be "dark mode". This could be a setting.

**Comment by krupenja** [comment]
Duplicate of #374

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
