### ISSUE TITLE
[Feature Request] Add feature to invert colours of a local pdf

### ISSUE THREAD

**Issue by shruti170901** [darkreader/darkreader#2562]
It would be really nice if the darkreader also inverts colours of pdf files local to the device similar to a feature of Adobe Reader

**Comment by Gusted** [comment]
![](https://i.imgur.com/CcWypp2.png) Exposed as 1 big element we can't touch any specific elements.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
