### ISSUE TITLE
[Feature Request] Invert PDFs Without Inverting Images Within

### ISSUE THREAD

**Issue by the-nelsonator** [darkreader/darkreader#3500]
First of all thanks for the great extension which has given eyeballs the world round a nicer time.

The invert PDF feature is great - but say you have a PDF with images (ex: https://ilab.org/sites/default/files/catalogs/files/Illustrated_Books_2019.pdf). Then you have to choose between the nice white on black text or actually seeing images how they're supposed to look. 

I tried looking for a "file," or "pdf" section in the dev tools customizer window, but couldn't find anything and I'm not sure if I'm just missing it. 

So if there isn't already some way to allow inverting pdfs without inverting images, could it be added?

![image](https://user-images.githubusercontent.com/23157710/90948562-ed3dd800-e3f4-11ea-97b1-ae857e84a6e2.png)

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
