### ISSUE TITLE
[Broken Website]  Gadgety website sometimes have its photos getting hidden

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [darkreader/darkreader#3643]
**Website**
The link of the broken website
https://www.gadgety.co.il/258305/lg-wing-announced/

**How to Reproduce**
An example of this is
> 1. Go to the website, and compare between light and dark theme. 

**Expected behavior**
Images should be visible.

**Actual behavior**
You can see that on dark theme, the images might get hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/5357526/93117637-d0c94e80-f6c7-11ea-90d2-83c461a680bf.png)

![image](https://user-images.githubusercontent.com/5357526/93117769-00785680-f6c8-11ea-9417-38e9265a5ccf.png)

**System info:**
 - OS: [e.g. Windows, MacOS, Linux]
Windows 10
 - Browser: [e.g. chrome, safari]
Chromium based 80.0.3987.163 (Cent Browser 4.2.10.171)
 - Darkreader Version: [e.g. 4.9.9]
4.9.19

 
**Additional context**
Would be nice if there was a setting to avoid modifying how images look .

**Comment by Gusted** [comment]
Hi @AndroidDeveloperLB!

The mode your using in Static and that isn't a ready to go style and should be modified itself for certain sites to make it look good.
If you want to have a quick fix use Filter(+) or Dynamic mode.



> Would be nice if there was a setting to avoid modifying how images look .

Fortunate we don't change any images it's rather the images is getting blocked by certain elements(their background-color).

Regards,
Gusted

**Comment by AndroidDeveloperLB** [comment]
Oh so it changes only the background?
But then how come I don't see the content of the images?

**Comment by Gusted** [comment]
> blocked by certain elements(their background-color).

Well, it seems like their are certain elements that lay on top of the image(z-index), that is filling that area with it's background-color.

**Comment by AndroidDeveloperLB** [comment]
Is it possible to choose only the main background instead?

**Comment by Gusted** [comment]
> Is it possible to choose only the main background instead?

Than you should edit the default stylesheet to specify this trough the devtools.

```CSS
/* Common theme */
html,
body,
:not([style*="background-color:"]) {
    background-color: rgb(16, 20, 23) !important;
}
html,
body,
:not([style*="color:"]) {
    color: rgb(167, 158, 139) !important;
}
h1:not([style*="color:"]),
h2:not([style*="color:"]),
h3:not([style*="color:"]),
h4:not([style*="color:"]),
h5:not([style*="color:"]),
h6:not([style*="color:"]) {
    color: rgb(247, 142, 102) !important;
}
cite:not([style*="color:"]) {
    color: rgb(128, 204, 148) !important;
}
input:not([style*="background-color:"]),
textarea:not([style*="background-color:"]),
button:not([style*="background-color:"]),
[role="button"] {
    background-color: rgb(32, 48, 64) !important;
}
input:not([style*="background-color:"]):hover,
textarea:not([style*="background-color:"]):hover,
button:not([style*="background-color:"]):hover,
[role="button"]:hover {
    background-color: rgb(30, 54, 78) !important;
}
input:not([style*="background-color:"]):active, input:not([style*="background-color:"]):focus,
textarea:not([style*="background-color:"]):active, textarea:not([style*="background-color:"]):focus,
button:not([style*="background-color:"]):active, button:not([style*="background-color:"]):focus,
[role="button"]:active, [role="button"]:focus {
    background-color: rgb(29, 56, 83) !important;
}
a:not([style*="color:"]) {
    color: rgb(128, 182, 204) !important;
}
a:not([style*="color:"]):hover {
    color: rgb(142, 193, 217) !important;
}
a:not([style*="color:"]):active, a:not([style*="color:"]):focus {
    color: rgb(155, 203, 230) !important;
}
:not([style*="border-color:"]),
::before,
::after {
    border-color: rgb(80, 115, 134) !important;
}
div:empty {
    background-color: rgb(16, 20, 23) !important;
}
input::placeholder,
textarea::placeholder {
    color: rgb(167, 158, 139) !important;
}
input:not([style*="background-image:"]),
textarea:not([style*="background-image:"]) {
    background-image: none !important;
}
```
