### ISSUE TITLE
Colors for ":before" in "Static" mode

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#375]
I using static theme, 'case it doesn't break page layout like Dynamic. But on static theme there is problems with some colors, like blue:
![image](https://user-images.githubusercontent.com/11363215/38899829-e43b1660-42a1-11e8-9b6c-4b31186c4b70.png)
Screenshot of [Bootrap Landing page](http://getbootstrap.com/)

**Comment by BANOnotIT** [comment]
Here is css code I found in page sources:

```css
.language-bash::before,
.language-sh::before {
  color: #009;
  content: "$ ";
  user-select: none;
}
```
