### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by Caesar2011** [darkreader/darkreader#3876]
**Website**

A google docs document with a Grammarly sidebar (which is still in beta and might change).

https://docs.google.com/document/d/xxxxxxxxxxxxxxxx/edit

**How to Reproduce**
An example of this is
> 1. Open a Google Docs File
> 2. Enable the Grammarly plugin on the right bottom corner
> 3. The suggestion boxes are to bright and should be dark as well as the background.

**Expected behavior**

The suggestion boxes are to bright...

**Actual behavior**

...and should be dark gray as well as the background.

**Screenshots**

![grammarly boxes](https://user-images.githubusercontent.com/6209109/96476687-d91c2880-1235-11eb-96b4-bb4eb6be10a5.png)

**System info:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Darkreader Version: 4.9.21

**Comment by Caesar2011** [comment]
Adding the following to the CSS section of docs.google.com worked fine for me:

```css
._60efd9e0-default-compactCardContainer,
._fe13e0b4-base-wrapper,
._14f6850e-base-activateBtn,
._2-NtU div[role="button"] {
    background-color: #333 !important;
}

._7a162ba9-default-highlightedText,
._ca4d018a-typography-base,
._95dcd592-replacements_labels-itemOriginalContent,
._bb023d25-typography-p1 {
    color: #aaa !important;
}
._fdfa38a2-button-tertiary:not([data-disabled="true"])[data-hovered="true"],
._d5be41ad-button-ghost:not([data-disabled="true"])[data-hovered="true"] {
    background: #222 !important;
}
._3j7oy {
    box-shadow: 0 -1px 0 #333 !important;
}

._3HRcY {
    background: linear-gradient(180deg,#333 91.58%,hsla(0,0%,100%,0)) !important;
}
```
