### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RashiqAzhan** [darkreader/darkreader#3933]
### **Describe the bug**

PDFs are darkened in chromium-based websites however such is not the case for Firefox.
I'm also not sure how all allow the Firefox extensions to allow access to local files as in chromium-based websites.

### **Steps to reproduce**

- Open any PDF document.

### **Expected behavior**

A dark PDF should appear.

### **Actual behavior**

PDFs are normal i.e. white.

### **Screenshots**

![image](https://user-images.githubusercontent.com/7370540/97196786-7e715800-1772-11eb-8632-cef4417c1e6c.png)
![image](https://user-images.githubusercontent.com/7370540/97196816-83cea280-1772-11eb-8c23-4950594ed2da.png)

### **System Information:**
 - OS: Windows 10 20H1
 - Browser: Firefox 82.0
 - Browser: Vivaldi 3.4.2066.76
 - Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
Dup #1541

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
