### ISSUE TITLE
[BUG] Highlighted text often not darkened properly

### ISSUE THREAD

**Issue by PowerUser64** [darkreader/darkreader#3960]
### **Description:**

In most cases, I have noticed that highlighted text is not handled well by darkreader, often making the highlighted text unreadable. 

### **Example:**
Take a look at the highlighted text in [this article](https://www.computerhope.com/issues/ch001391.htm). Notice how the highlighted text at the top is almost unreadable because it is light-colored. Yet, if you scroll down on that to the section titled "Highlight using the HTML5 \<mark\> tag", you'll notice that the highlighted text in that paragraph is black.

### **The problem**

The issue is that there are two ways to highlight text; one is with the \<mark> tag, with the other, more problematic way, being to set the background color of the text to whatever color you want to highlight it in (both ways are shown below).
```html
<span style="background-color: #FFFF00">Yellow background</span>
<mark>Highlighted with the mark tag</mark>
```
I do see that darkreader changes the HTML element (as seen below), adding some CSS, but it doesn't seem to work quite right
```html
<span style="background-color: rgb(255, 255, 0); --darkreader-inline-bgcolor:#cecc08;" data-darkreader-inline-bgcolor="">Yellow background</span>
```
### **System Information:**
 - OS: manjaro linux (kernel 5.9)
 - Browser: Firefox 82.0.1
 - Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
> Take a look at the highlighted text in [this article](https://www.computerhope.com/issues/ch001391.htm). Notice how the highlighted text at the top is almost unreadable because it is light-colored. Yet, if you scroll down on that to the section titled "Highlight using the HTML5 <mark> tag", you'll notice that the highlighted text in that paragraph is black.

This site, implements a simple CSS code for custom highlighting which unfortunely uses `Yellow` what is for Dark Reader an tricky color to work with because the contrast is different then other colors and because this the paragraph is styled with the same color as the `span` it won't modify the color as their isn't specified one.

> I do see that darkreader changes the HTML element (as seen below), adding some CSS, but it doesn't seem to work quite right

Dark reader does it's work however the end result isn't expected and isn't read-able, however the `mark` element seems to be styled right.

You mention `often` so does this problem relies on other sites as well?

Regards,
Gusted

**Comment by PowerUser64** [comment]
> You mention `often` so does this problem relies on other sites as well?

Yes, this issue has bothered me for a while. I never thought to open an issue until I was forced to use light theme on my college's [canvas](https://www.instructure.com/canvas/) page when I noticed couldn't read highlighted text. However, there are plenty of other examples scattered across the internet.

**Comment by Gusted** [comment]
> [canvas](https://www.instructure.com/canvas/) page because I couldn't read highlighted text.

Could you point out where the highlighted text is?

**Comment by PowerUser64** [comment]
Unfortunately, I don't think I can get you access to the page's complete source without giving you access to my account. However, I can certainly give you some of the broken html elements, along with a stylesheet. Does this help?

# Some `Code`

## Darkreader OFF
### Screenshot:
![Screenshot from 2020-11-09 01-34-14](https://user-images.githubusercontent.com/24578572/98524556-36e7d300-222c-11eb-88be-f282483f27ee.png)


### HTML:
```html
<span style="background-color: #00ff00;"><strong>Homework To-Do List</strong></span>
<span style="background-color: #ffff00;"><strong>Homework due Wednesday (9/16) </strong></span>
<span style="background-color: #ffff00;"><strong>by 4 p.m.</strong></span>
```
### CSS (h2 tag):
```css
h1, h2, .h1, .h2 {
	font-size: 1.8em;
	line-height: 1.5;
}
h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
	font-weight: normal;
}
h2 {
	font-size: 32px;
}
h1, h2, h3, h4, h5, h6 {
	margin: 6px 0;
	font-family: "Lato Extended","Lato","Helvetica Neue",Helvetica,Arial,sans-serif;
	font-weight: bold;
	line-height: 1.5;
	text-rendering: optimizelegibility;
}
```
### CSS (paragraph tags):
```css
element {
	padding-left: 40px;
}
p {
	margin: 12px 0;
}
```

## Darkreader ON (Broken)
##### *Default settings on Dynamic mode*
### Screenshot:
![Screenshot from 2020-11-09 00-50-44](https://user-images.githubusercontent.com/24578572/98520038-6693dc80-2226-11eb-8b2e-4753b4fab80c.png)

### HTML:
```html
<span style="background-color: rgb(0, 255, 0); --darkreader-inline-bgcolor:#33cc00;" data-darkreader-inline-bgcolor=""><strong>Homework To-Do List</strong></span>
<span data-darkreader-inline-bgcolor="" style="background-color: rgb(255, 255, 0); --darkreader-inline-bgcolor:#cccc00;"><strong>Homework due Wednesday (9/16) </strong></span>
<span style="background-color: rgb(255, 255, 0); --darkreader-inline-bgcolor:#cccc00;" data-darkreader-inline-bgcolor=""><strong>by 4 p.m.</strong></span>
```
### CSS (h2 tag):
```css
element {
}
h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
	font-weight: normal;
}
h2 {
	font-size: 32px;
}
h1, h2, h3, h4, h5, h6 {
	margin: 6px 0;
	font-family: "Lato Extended","Lato","Helvetica Neue",Helvetica,Arial,sans-serif;
	font-weight: bold;
	line-height: 1.5;
	text-rendering: optimizelegibility;
}
* {
	scrollbar-color: #202324 #454a4d;
}
```
### CSS (paragraph tags):
```css
body {
	color: rgb(205, 200, 194);
}
body {
	/* font-size: 16px; */
	font-size: 1rem;
	font-weight: normal;
	line-height: 1.5;
	color: var(--ic-brand-font-color-dark);
}
body {
	font-weight: 300;
}
html, body, input, textarea, select, button {
	color: #e8e6e3;
}
```

**Comment by Gusted** [comment]
Because it's some custom style that doesn't apply a contrast-ratio based color.... it will have the old color so a simple fix like.
```CSS
span[data-darkreader-inline-bgcolor] {
    color: #181a1b !important
}
```
Should make those elements visible, but that selector could mess up other elements... So using Stylus on those site with the CSS fix should do the trick.

Regards,
Gusted
