### ISSUE TITLE
[BUG] DarkReader sometimes ignores Stylus CSS variable overrides

### ISSUE THREAD

**Issue by NSExceptional** [darkreader/darkreader#3972]
### **Describe the bug**

DarkReader seems to ignore CSS variable overrides set with Stylus. My overrides work when DarkReader is off, but not when it is on. For example, if the site has the following CSS:

```css
:root {
    --code-color: red;
}
code {
    color: var(--code-color);
}
```
and I use this CSS in Stylus:
```css
:root {
    --code-color: green !important;
}
```
The `code` text will appear green when DarkReader is off, but when DarkReader is on, it will appear as the inversion of the red color. 

### **Steps to reproduce**

I tried to reproduce this on GitHub by overriding the `--color-border-secondary` color, but it worked. I don't know what's happening with this other site. It is our local-intranet Confluence page.

### **System Information:**
 - OS: Windows 10 1809
 - Browser: Chrome 85
 - Dark Reader version: 4.9.22

### **Additional context**

Even if I "uncheck" all of the relevant CSS variables in the developer tools, the "constructed stylesheet" from DarkReader does not change. You would expect it to change when the underlying variables change, no?
