### ISSUE TITLE
L'internaute - synonymes

### ISSUE THREAD

**Issue by mikerouxfr** [darkreader/darkreader#4299]
**Website**
https://www.linternaute.fr/dictionnaire/fr/definition/tester/

**How to Reproduce**
> 1. Scroll down to the "Synonymes" section
> 2. See that the section is barely readable

**Expected behavior**
The container should gets a darkened background a lengthened text.

**Actual behavior**
Nothing happen to this section because the website's css overrides it (selector higher priority).

**Screenshots**
![image](https://user-images.githubusercontent.com/9786566/100455733-7ed97780-30bf-11eb-8fe2-7769f2a4ee23.png)

**System info:**

- OS: Windows 10 Pro 20H2 (19042.630)
- Browser: Firefox Developer 84.0b4 (64 bits)
- Darkreader Version: 4.9.25

**Additional context**
So far, my suggested snippet to fix looks like this but it doesn't work with Light mode.
```css
================================

linternaute.fr

INVERT
.dico_liste.grid_line > li

CSS
.dico_liste_greyandwhite .dico_liste li a {
    color: var(--darkreader-neutral-background);
}
```
