### ISSUE TITLE
[Broken Website] grasshopper.app

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4461]
**Website**
The link to the broken website

grasshopper.app

**How to Reproduce**

Note: Owned By Google

An example of this is
>
> 1. Go to grasshopper.app site
> 2. Sign up with google
> 3. Start a course
> 4. Screen is blank (gray/black)
> 5. Turn off dark mode
> 6. The interface appears again

**Expected behavior**

Interface to appear

**Actual behavior**
A clear and concise description of what happened.

Blank screen

**Additional context**

I think some element might have a higher `z-index`, placing it above everything.

**Comment by Yash-Singh1** [comment]
**UPDATE**

The colors in static mode in `darkreader` do not have any transparency. Everything has a background color messing up the whole page. After switching the color in the styles:
```css
html,
body,
:not([style*="background-color:"]) {
    background-color: rgb(16, 20, 23) !important;
}
```
 to:
```css
html,
body,
:not([style*="background-color:"]) {
    background-color: rgba(16, 20, 23, 0.25) !important;
}
```
It worked again.

Before:
![Screenshot from 2020-12-09 10-49-26](https://user-images.githubusercontent.com/53054099/101673780-74e33d00-3a0c-11eb-927b-1cc00b7dbd42.png)
After:
![Screenshot from 2020-12-09 10-51-20](https://user-images.githubusercontent.com/53054099/101673811-7f9dd200-3a0c-11eb-877a-2f806d8910a1.png)
