### ISSUE TITLE
Reading a PDF on Chrome and Edge

### ISSUE THREAD

**Issue by anoldmaninthesea** [darkreader/darkreader#4497]
When reading a pdf online, Dark Reader correctly inverts colours, just like in this link: http://ftp.iza.org/dp7520.pdf

However, when I download the file, and I want to read it offline on Chrome, or Edge, Dark Reader does not invert the pdf's colours... 

I was wondering if it would be possible to add a feature where Dark Reader would invert colours for an offline file, while using Chrome or Edge.

Kind regards.

**Comment by Gusted** [comment]
https://darkreader.org/help/en/#the-extension-doesnt-work-for-local-files

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
