### ISSUE TITLE
[Broken Website] contabo.com

### ISSUE THREAD

**Issue by kizule** [darkreader/darkreader#4752]
https://contabo.com got a new, fresh update. :)
But, some elements are incorrectly inverted, like .svelte-ydcnhq (First-class Customer Support box) and few others below. It should be fixed.
![image](https://user-images.githubusercontent.com/28963303/104389321-72a85d00-553b-11eb-878f-5ef5ae349f32.png)
![image](https://user-images.githubusercontent.com/28963303/104389349-85229680-553b-11eb-97ad-8869feb1d43c.png)

**System info:**

- OS: Windows 10
- Browser: Opera Gaming LVL2 (core: 72.0.3815.465)
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
Most are fixed by #4291

**Comment by AndrewDaGuy** [comment]
Should we close this as #4291 is merged?

**Comment by Gusted** [comment]
> Should we close this as #4291 is merged?
> 
> Edit: Just went on the website it looks like its broken still? :/

Inline variables are currently not supported.

**Comment by AndrewDaGuy** [comment]
> > Should we close this as #4291 is merged?
> > Edit: Just went on the website it looks like its broken still? :/
> 
> Inline variables are currently not supported.

Ah, no wonder the retina-burning-white is still there

**Comment by ModProg** [comment]
The configuration page my.contabo.com also had some issues, I added this to improve it:
```css
================================

my.contabo.com

CSS
#mainmenu {
    background-color: rgb(0, 0, 111) !important;
    border-radius: 20px 0px 0px 20px !important;
    box-shadow: -2px -2px, -2px 2px, 0px 2px, 0px -2px !important;
}
#mainmenu > div {
    background-image: none !important;
}
#submenu {
    background-color: #977122 !important;
    border-radius: 20px 0px 0px 20px !important;
    box-shadow: -2px -2px, -2px 2px, 0px 2px, 0px -2px !important;
}
#submenu > div {
    background-image: none !important;
}
.button {
    background-image: linear-gradient(#126382 49%, #0a4f6a 51%);
}
```

This is how it looks now:
![grafik](https://user-images.githubusercontent.com/11978847/135713114-7e5cf7b5-e137-4f54-85d7-1bea96d3cc45.png)

This is how it looked before:
![grafik](https://user-images.githubusercontent.com/11978847/135713126-58ab9fe5-676b-41b4-aafb-11420dd53bf2.png)
