### ISSUE TITLE
[Broken Website] GitLab sidebar close button

### ISSUE THREAD

**Issue by cromefire** [darkreader/darkreader#4764]
**Website**
https://gitlab.com/factory-org/tools/gradle-go/-/requirements_management/requirements?state=opened

**How to Reproduce**
An example of this is
1. Click on a requirement

**Expected behavior**
The close button (top-right) should be visible (contain a white icon in dark mode).

**Actual behavior**
The icon stays black and is new invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/26320625/104463205-c5bcf700-55b1-11eb-9174-2e331661aad6.png)

**System info:**

- OS: Linux
- Browser: Firefox 84.0.2
- Darkreader Version: 4.9.26

**Additional context**
I've tried a lot of things (custom css, explicit conversion, etc.), but I only got the button to be even darker.

**Comment by Gusted** [comment]
Hi @cromefire!

I had a look at the close button and it seems to be an [shadow-root](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) which is [closed](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode) meaning we can do little to nothing to fix this close button. I tried various ways but the end result is either not possible to add into CSS or the button straight up disappears. 

Regards,
Gusted

**Comment by cromefire** [comment]
I was thinking that maybe one could at least make the button background white, but I wasn't able to get that working (it always ended of not making a difference or being even darker).

**Comment by Gusted** [comment]
> but I wasn't able to get that working (it always ended of not making a difference or being even darker).

That was my problem too, their seems to be some kind of CSS effect affecting this. I'm unsure which CSS is doing this.

**Comment by cromefire** [comment]
The problem seems to be the `mix-blend-mode: multiply;`. setting it to `unset` might work, I'll try that

**Comment by cromefire** [comment]
I got some working css:
```css
.gl-drawer-close-button {
    background-color: #fafafa !important;
    mix-blend-mode: unset !important;
}
```
can I somehow make it only be active in darkmode?

**Comment by Gusted** [comment]
> can I somehow make it only be active in darkmode (it's slightly off in light mode otherwise)?

```CSS
.gl-drawer-close-button {
    color: var(--darkreader-neutral-color) !important;
    mix-blend-mode: unset !important;
}
```
Should do the job for dark/light mode.
