### ISSUE TITLE
pdf reading with dark reader

### ISSUE THREAD

**Issue by DudeYes** [darkreader/darkreader#5581]
# Feature Request

**Comment by Skribbles64** [comment]
Can you add this to the Firefox version?
(I noticed that it isn't there.)
![image](https://user-images.githubusercontent.com/94587115/215857817-7bf90ebd-dd2f-4552-a3fd-4ae3d88d0451.png)![image](https://user-images.githubusercontent.com/94587115/215858071-a09c6edb-e235-4028-a9a8-f3d63777e170.png)

**Comment by akasyagroup** [comment]
https://github.com/darkreader/darkreader/issues/5581#issuecomment-1410919960

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
