### ISSUE TITLE
PDF Reader looks weird

### ISSUE THREAD

**Issue by GauthierPLM** [darkreader/darkreader#57]
Hi,

In night mode, Chrome' PDF reader looks very strange as borders are really clear with a darker part for the PDF itself.

It would be better if background and top bar had darker grey in night mode.

![capture](https://cloud.githubusercontent.com/assets/2579741/21628780/4d5c3ec2-d222-11e6-8b8d-d1c5304d8a72.PNG)

**Comment by BANOnotIT** [comment]
@Kendos-Kenlen, PDF reader is builtin chrome plugin, so I think that it's hard to change parts of it view...

**Comment by alexanderby** [comment]
SVG filter was implemented, there should be possibility to modify the inversion region

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
