### ISSUE TITLE
[Broken Website] HyperPhysics

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#5902]
# Broken Website
## Website

http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html

## Expected behavior

Images as clear as in light mode.

## Actual behavior

Images in dark mode are not very legible.

## Screenshots

![pic-selected-210529-1346-39](https://user-images.githubusercontent.com/59497618/120063345-5a695280-c084-11eb-96db-6b32bb3de36c.png)

## System Information

- OS:  Linux
- Browser:  Firefox 88
- Dark Reader Version:  4.9.33

**Comment by AndrewDaGuy** [comment]
I can't seem to fix this with
```css
INVERT
img
img[src*="imgqua/comptonr.gif"]
```
or
```css
/* The problem with this one is that body has the attribute "bgcolor" which I think dark reader doesn't change :c */
CSS
body {
   background-color: var(--darkreader-neutral-background) !important;
}
```

Gonna leave this for anyone else to fix this :c
