### ISSUE TITLE
[BUG] change background color not work on arxiv pdf 

### ISSUE THREAD

**Issue by twangnh** [darkreader/darkreader#6162]
The background color customization works on normal websites, but with an arxiv site for example, https://arxiv.org/pdf/2009.00437.pdf, it still gives background of black as default, could you pls fix this bug? Thanks!

**Comment by Gusted** [comment]
Hi @twangnh!

Are you on Firefox on Chromium?

**Comment by twangnh** [comment]
I'm using google chrome

**Comment by Gusted** [comment]
That's a bummer, because we cannot do anything about that. Chromium restricts pretty much everything on PDF's. Other than 1 object which represents the whole UI + the document itself.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
