### ISSUE TITLE
[Broken Website] cVim plugin

### ISSUE THREAD

**Issue by colossatr0n** [darkreader/darkreader#6221]
# Broken Plugin
## cVim Plugin

https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh

## How to Reproduce
I'm having an issue using the Dynamic Theme Editor to override the styling of cVim link hints in dark mode. If I try to override `.cVim-link-hints`, the changes don't come into effect, and instead get overwritten again by Dark Reader.

## Expected behavior
I should be able to override the link hints CSS in the Dynamic Theme Editor, but when I inspect the CSS changes in Chrome Dev Tools, the override added in the Dynamic Theme Editor keeps getting overwritten as shown by the Chrome Dev Tools.  

## Actual behavior
If I update a CSS class in the Dynamic Theme Editor, that override should take precedence over anything else.

## Screenshots
Let's say that I want to always make the link hint background black, so I add the following to the Dynamic Theme Editor:
```css
*
[...]

CSS
.cVim-link-hint {
    background-color: black !important;
}
```

When I inspect the CSS changes in Chrome Dev Tools, the black background color is somehow superseded by the inversion of the light mode link hint colors.

Here are the default link hint colors (light-mode or Dark Reader disabled):
```css
/* Normal colors */
.cVim-link-hint {
    color: #302505 !important; /* blackish and striked through in Chrome Dev Tools */
    background-color: #ffd76e !important; /* light yellowish and striked through in Chrome Dev Tools*/
    border: 1px solid #ad810c; /* orange/goldish */
}
```

Here are the resulting inverted colors (dark mode). You can see that the `background-color: black !important` override was ignored:
```css
/* Dark mode */
.cVim-link-hint {
    color: rgb(215, 212, 207) !important; /* white */
    background-color: rgb(138, 100, 0) !important; /* brownish */
    border-color: rgb(187, 139, 13); /* orange/goldish */
}
```

Here is the background color override that was added to the Dynamic Theme Editor:

```css
.cVim-link-hint {
    background-color: black !important; /* striked through in Chrome Dev Tools */
}
```
I'm unsure why the Dynamic Theme Editor override is being ignored.

## System Information

- OS: macOS, Linux
- Browser: Chrome 91
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Hi @colossatr0n!

First off, I don't recommend using the Dynamic Theme editor for permanent CSS Changes that don't end up in the config file, as it's highly likely to get overwritten at any time.

Thereby, this is expected behavior as the cVim's style itself and our `--sync` style is on a "lower" children's level and thus takes priority over any previous elements(the `--override` style). You can overwrite this behavior by using something like:

```CSS
div.cVim-link-hint {
    background-color: black !important;
}
```

Regards,
Gusted
