### ISSUE TITLE
[Feature Request] Option to exclude images from inverting colors

### ISSUE THREAD

**Issue by steph643** [darkreader/darkreader#6894]
# Feature Request

## Is this feature request related to a problem?
In some cases it's better when you can keep dark mode on but you need original image colors instead of inverted colors.

## Screenshots
For example, try to purchase a butter dish on Amazon:
with Dark Reader on:
![image](https://user-images.githubusercontent.com/7039479/134697467-9924afd8-ce9d-4f66-be26-fe0f75c5579c.png)
with Dark Reader off:
![image](https://user-images.githubusercontent.com/7039479/134697501-8774b5ab-8243-4f0b-aaec-f03264619eff.png)
And of course it's much worth if you want to purchase paint!

## Additional Context
On the web, images have two purposes: 1. decorating and 2. actually showing something (products, tutorials, art, etc., etc.). From a Dark  Reader perspective, images for decoration should be modified, the other ones should not. Of course Dark  Reader doesn't know which way it is, but luckily websites with one kind of images usually don't have many of the other kind. So a "per website" option is all what's needed.

**Comment by Gusted** [comment]
Hi @steph643!

Thanks for creating the separate issue.

Given the example is now used with Amazon, I had a look at the butter dish products and I couldn't find any CSS whereby we're modifying the images. We've been pretty lax to not modify any standalone images. So in this case It's a bit hard to implement a option which doesn't do anything as we do not touch standalone images.

I do see from the screenshot that the image are "brighter" with dark reader is on. This is pretty as just explained, we do not have code to do that. So I'm not really sure how you got that.

Regards,
Gusted

**Comment by steph643** [comment]
Thanks a lot, @Gusted, how mysterious :-)

When I inspect my Amazon page, I do find a Dark Reader-like CSS on images:
```css
img, 
video, 
:not(object):not(body)>embed, 
object, 
svg image, 
[style*="background:url"], 
[style*="background-image:url"], 
[style*="background: url"], 
[style*="background-image: url"], 
[background], 
twitterwidget, 
.sr-reader, 
.sr-backdrop {
    filter: invert(100%) hue-rotate(180deg) !important;
}
```
However, when I open Dark Reader Dev tools, I can find no "hue-rotate" there.

Any idea what's wrong?
