### ISSUE TITLE
[Broken Website] vk.com/doc*

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#6941]
# Broken Website Report

## Website Address
https://vk.com/doc13291248_602127644?hash=9c58a3923d5946d70d&dl=93ed2d8aacdab4b012

## Steps To Reproduce
- Go to https://vk.com/doc13291248_602127644?hash=9c58a3923d5946d70d&dl=93ed2d8aacdab4b012

## Expected Behavior
The content of the doc file is inverted.

## Actual Behavior
The content of the doc file is not inverted.

## Screenshots

<details>
<summary>Sceenshot</summary>

![Sceenshot](https://user-images.githubusercontent.com/19418601/135100137-e4b54bb0-7b40-4e28-bda0-4e63789d6b66.png)

</details>

## System Information
- OS: Windows 10
- Browser: Chrome 94
- Dark Reader Version: 4.9.38

## Additional Context
It looks like a problem with Shadow root, since the `INVERT img` or `INVERT .WACPageImg` rules do not affect the page in any way.

**Comment by Gusted** [comment]
Hi @rakleed!

Are their are any DR-related styles(`darkreader--override`) in the shadowroot? 

Regards,
Gusted

**Comment by rakleed** [comment]
@Gusted yes:

<details>
<summary>Details</summary>

```css
<style class="darkreader darkreader--override" media="screen">.vimvixen-hint {
    background-color: #7b5300 !important;
    border-color: #d8b013 !important;
    color: #f3e8c8 !important;
}
::placeholder {
    opacity: 0.5 !important;
}
a[href="https://coinmarketcap.com/"] > svg[width="94"][height="16"] > path {
    fill: var(--darkreader-neutral-text) !important;
}
#edge-translate-panel-body {
    color: var(--darkreader-neutral-text) !important;
}
gr-main-header {
    background-color: #0f3a48 !important;
}
embed[type="application/pdf"] { filter: invert(100%) contrast(90%); }</style>
```

</details>
