### ISSUE TITLE
[Broken Website] atlassian.net

### ISSUE THREAD

**Issue by ModProg** [darkreader/darkreader#7016]
# Broken Website Report

## Website Address
I noticed the issue on an internal page, but I expect this to affect Atlassian in general.

## Steps To Reproduce
- Look at an inline code part in e.g. Confluence:
```md
`name`
```
- notice that the background only affects the beginning of the inline code

## Expected Behavior
The whole code snippet should have a highlighted background

## Actual Behavior
Only the beginning is highlighted

## Screenshots
![grafik](https://user-images.githubusercontent.com/11978847/136177522-2f966d66-2d9d-47ea-8777-d15a6ccf7106.png)
![grafik](https://user-images.githubusercontent.com/11978847/136177853-93ca9732-691b-4927-8254-2825125fc938.png)

## System Information

- OS: Windows
- Browser: Firefox 92.0.1
- Dark Reader Version:  4.9.39

**Comment by ModProg** [comment]
One more thing I noticed that is kind of annoying to fix is the edit mode, due to
```
IGNORE INLINE STYLE
.ak-editor-content-area *
```
Inline styles are not evaluated.

I added these two rules to fix it for my use case, but obviously there are more colors.
```css
.ak-editor-content-area [colorname="Light green"] {
  background-color: #073f29 !important;
}
.ak-editor-content-area [colorname="Light teal"] {
  background-color: #003a42 !important;
}
```
