### ISSUE TITLE
[Broken Website] AWS Console

### ISSUE THREAD

**Issue by KyranRooks** [darkreader/darkreader#7027]
# Broken Website Report

## Website Address
https://ap-southeast-2.console.aws.amazon.com/

## Expected Behavior

White space should become inverted to black

## Actual Behavior

White space remains white. Text still inverts, making it very hard to read

## Screenshots

![image](https://user-images.githubusercontent.com/92070529/136314218-c207e21f-f21c-4e30-bf61-2055836b1b63.png)

## System Information

- OS: Windows 10. Build 19043
- Browser: Google Chrome 94.0.4606.71 (Official Build) (64-bit)
- Dark Reader Version: 4.9.39

## Additional Context
This started happening around the time of the latest release of the Dark Reader Google Chrome extension.

**Comment by gregk-git** [comment]
Can confirm, have the same issue.
Using the old EC2 console fixes the issue (you can switch with that big blue toggle button in the top left, called "New EC2 Experience"), but Dark Reader worked fine on the new EC2 Console up until very recently.

**Comment by tmpm697** [comment]
+1

**Comment by BlackDex** [comment]
@Gusted I think i have found the CSS which is causing this.
In the code below i commented out the culprit part, which makes it dark again for me.

The strange thing is, can't seem to be able to see that in the original code anywhere. I'm either not dev-tools savvy enough or looking completely at the wrong place.
```css
.awsui_root_14iqq_b7qqk_3:not(#\9){
  border-collapse:separate;
  border-spacing:0;
  caption-side:top;
  cursor:auto;
  direction:ltr;
  empty-cells:show;
  font-family:serif;
  font-size:medium;
  font-style:normal;
  font-variant:normal;
  font-weight:normal;
  font-stretch:normal;
  line-height:normal;
  hyphens:none;
  letter-spacing:normal;
  list-style:disc outside none;
  tab-size:8;
  text-align:left;
  text-align-last:auto;
  text-indent:0;
  text-shadow:none;
  text-transform:none;
  visibility:visible;
  white-space:normal;
  widows:2;
  word-spacing:normal;
  box-sizing:border-box;
  font-size:14px;
  font-size:var(--font-body-m-size-mm2q-F, 14px);
  line-height:22px;
  line-height:var(--font-body-m-line-height-Au__lG, 22px);
/*   color:#16191f;
  color:var(--color-text-body-default-1vaq0d, #16191f); */
  font-weight:400;
  font-family:"Amazon Ember", "Helvetica Neue", Roboto, Arial, sans-serif;
  font-family:var(--font-family-base-313bNQ, "Amazon Ember", "Helvetica Neue", Roboto, Arial, sans-serif);
  display:block;
  word-wrap:break-word;
}
.awsui_root_14iqq_b7qqk_3:not(#\9):not(.awsui_root-disable-content-borders_14iqq_b7qqk_14){
  box-shadow:0 1px 1px 0 rgba(0, 28, 36, 0.3), 1px 1px 1px 0 rgba(0, 28, 36, 0.15), -1px 1px 1px 0 rgba(0, 28, 36, 0.15);
  box-shadow:0 1px 1px 0 var(--color-shadow-medium-2hS7JG, rgba(0, 28, 36, 0.3)), 1px 1px 1px 0 var(--color-shadow-side-2gBR7T, rgba(0, 28, 36, 0.15)), -1px 1px 1px 0 var(--color-shadow-side-2gBR7T, rgba(0, 28, 36, 0.15));
  border-top:1px solid #eaeded;
  border-top:var(--border-field-width-1LKjCO, 1px) solid var(--color-border-container-top-1gYBaj, #eaeded);
  border-radius:0px;
  border-radius:var(--border-container-radius-1N6yDL, 0px);
  box-sizing:border-box;
/*   background-color:#ffffff;
  background-color:var(--color-background-container-content-kY-kln, #ffffff); */
}
```

**Comment by BlackDex** [comment]
Small update, a little bit traversing back the HTML tree i got this:
```css
.awsui_root_14iqq_b7qqk_3:not(#\9 ):not(.awsui_root-disable-content-borders_14iqq_b7qqk_14) {
  box-shadow: 0 1px 1px 0 rgba(0, 28, 36, 0.3), 1px 1px 1px 0 rgba(0, 28, 36, 0.15), -1px 1px 1px 0 rgba(0, 28, 36, 0.15);
  box-shadow: 0 1px 1px 0 var(--color-shadow-medium-2hS7JG, rgba(0, 28, 36, 0.3)), 1px 1px 1px 0 var(--color-shadow-side-2gBR7T, rgba(0, 28, 36, 0.15)), -1px 1px 1px 0 var(--color-shadow-side-2gBR7T, rgba(0, 28, 36, 0.15));
  border-top: 1px solid #eaeded;
  border-top: var(--border-field-width-1LKjCO, 1px) solid var(--color-border-container-top-1gYBaj, #eaeded);
  border-radius: 0px;
  border-radius: var(--border-container-radius-1N6yDL, 0px);
  box-sizing: border-box;
  background-color: #ffffff;
  background-color: var(--color-background-container-content-kY-kln, #ffffff);
}
```
If i disable this specific rule, all is fine again.
