### ISSUE TITLE
[Bug] Dark Reader keeps deleting my CSS additions in developer tools

### ISSUE THREAD

**Issue by JackDjTom** [darkreader/darkreader#7510]
# Bug Report

## Bug Description
When I configure the style of a certain website with the Developer Tools (Dynamic Theme Editor) and then close and reopen the browser, the changes I made are lost.

## Steps To Reproduce

- Click on Dark Reader Addon
- Select Advanced
- Add a new style for the website you want to customize
e.g.:
```css
================================

my-webiste.com

CSS
div[class*=' issue'],div[class^='issue'] {
     background-color: rgb(44, 44, 44)
}
```
- Hit Apply
- The customized Style is applied.
- Close and Reopen Browser.
- The customization is lost.

## Expected Behavior

The customization is still there after reopening the browser.

## Actual Behavior

The customization is lost.

## System Information

- OS: Windows 
- Browser: Chrome 96.0.4664.45 
- Dark Reader Version: 4.9.42
