### ISSUE TITLE
[Bug] Edge Chromium PDF Viewer inverting Background color

### ISSUE THREAD

**Issue by JM-Lemmi** [darkreader/darkreader#7684]
# Bug Report

## Bug Description

The Edge Chromium PDF Viewer Inverts the color of the PDF (as expected), but also inverts the color of the background to white.

## Steps To Reproduce

- Enable DarkReader acces to files in Edge Settings (Extensions/Installed Extensions/DarkReader/Allow access to file URLs)
- Open PDF
- Enable Dark Reader for PDF with the Toggle Button top left of the extension
- Set Engine to Filter, Filter+ or Dynamic

## Expected Behavior

The Background should stay in its original black color.

## Actual Behavior

The Background inverts color to white.

## Screenshots

![image](https://user-images.githubusercontent.com/41118534/146658261-eb032e0a-a2a0-4998-b6b7-5c6884093e1a.png)

## System Information

- OS: Windows 11 21H2 Build 22000.376
- Browser: Edge 96.0.1054.62
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Duplicate of #3585

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
