### ISSUE TITLE
[Dynamic] FreeBitcoin background

### ISSUE THREAD

**Issue by bgiesing** [darkreader/darkreader#770]
![](https://i.imgur.com/JyhSQXy.png)

I tried using the dev tools to find a fix to submit via the `dynamic-theme-fixes.config` file it but it seems the background image is directly tied to the body with no other class or id associated so it's impossible to remove as using `INVERT` on the whole body would screw up everything else. Since it's dynamic mode, you also can't just use `REMOVE BG` like Filter+

The CSS used on the page:
```css
body {
    background: #E6E6E6 url(/images/website_background_whitewall4.png);
}
```
