### ISSUE TITLE
freiheitsfonds.de: background image missing

### ISSUE THREAD

**Issue by TalviT** [darkreader/darkreader#7916]
I noticed that with Dark Reader enabled, the background image of [freiheitsfonds.de](https://freiheitsfonds.de) is missing:

Dark Reader off:
![Screenshot 2022-01-10 at 23-39-41 Freedom Fund](https://user-images.githubusercontent.com/18188251/148851325-bdcb50fd-2dc3-4b99-86e3-e0a6f098716b.png)

Dark Reader on:
![Screenshot 2022-01-10 at 23-39-53 Freedom Fund](https://user-images.githubusercontent.com/18188251/148850911-0a31ca4d-ef25-4980-be66-9f97fd4dfaca.png)

 so I tried to make a darkened version of it visible again with:

```css
freiheitsfonds.de

CSS
.hero {
    background-image: url(img/hero-bg.jpg) !important;
    filter: brightness(50%) !important;
}
```

This kinda works, but it breaks the parallax functionality. Also, `filter` causes the language button to disappear. Now my knowledge is too limited on this field to fix this by myself, so maybe some of you can find a better solution.
