### ISSUE TITLE
[Bug] Miss -webkit-linear-gradient

### ISSUE THREAD

**Issue by caoccao** [darkreader/darkreader#8178]
# Bug Report

## Website Address

[Sample Website](https://www.cnbeta.com/)

## Bug Description

Dark Reader seems to ignore disabling `-webkit-linear-gradient` so that the `--darkreader-neutral-background` is overridden by the `-webkit-linear-gradient`.

```css
.cnbeta-update-list .item {
  background: -webkit-linear-gradient(top,rgb(255 255 255),rgb(255 255 255) 100%);
}
```

## Steps To Reproduce

Just visit the [Sample Website](https://www.cnbeta.com/), and you will notice the major area is in white.

## Expected Behavior

The major area is expected to be in black.

## Actual Behavior

The major area is in white.

## Screenshots

![2022-02-09_12-33-04](https://user-images.githubusercontent.com/17514279/153122436-56649302-443a-4ffa-84ed-16c72532896f.png)

![2022-02-09_12-35-37](https://user-images.githubusercontent.com/17514279/153122661-4860afd4-5f41-4850-ad79-bb2f1161490a.png)

## System Information

- OS: Windows 10
- Browser: Chrome 97
- Dark Reader Version: 4.9.45
