### ISSUE TITLE
[Bug] With `Detect dark theme` turned on, PDF files are not inverted

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#8452]
# Bug Report

## Website Address

https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

## Bug Description

With `Detect dark theme` feature turned on, PDF files are not inverted.

## Steps To Reproduce

- Turn on `Detect dark theme` feature in DarkReader Settings
- Go to https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
- Make sure that DarkReader enabled for PDF files

## Expected Behavior

PDF file is inverted.

## Actual Behavior

PDF file is not inverted.

## Screenshots

<details><summary>Screenshots</summary>

![2022-03-16_13-03-29](https://user-images.githubusercontent.com/19418601/158565700-a91f152f-60f1-4aa6-ba3b-7b2add01abed.png)

![2022-03-16_13-03-48](https://user-images.githubusercontent.com/19418601/158565713-6a1515e6-a5f0-42e2-96b1-f6e2967522ed.png)

</details>

## System Information

- OS: macOS
- Browser: Chrome 99
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/8453

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
