### ISSUE TITLE
[Performance Issue] Replace with title

### ISSUE THREAD

**Issue by MichaelFlucher** [darkreader/darkreader#8590]
# Performance Issue Report

## Website Address
Company Internal Jira instance

## Steps To Reproduce

- only happens, when I define some custom CSS for this specific subdomain of *.atlassian.net
- when I hit edit on a page everything hangs and the cpu consumption is very high
- after a few seconds I get RESULT_CODE_HUNG in chrome

## Performance Profile
Cannot record, as the tab hangs forever

## System Information

- OS: 
- Browser: Chrome Version 99.0.4844.51 (Official Build) (32-bit) 
- Dark Reader Version: 4.9.47 

## Additional Context
- Does this happen when Dark Reader is disabled? --> no
- Does this happen in other browsers? --> yes, also tried with edge
- Do you have hardware acceleration enabled? --> i don't know

The custom CSS I added is the following one. I also tried to simply remove some of the blocks, but as soon as there is a custom CSS for the page defined everything blocks after I enter the edit mode.
```css
================================
mysubdomain.atlassian.net
CSS
#ak-main-content, .css-cdxr6t {
    background-color: #181a1b !important;
}
.css-1nfsqgt, .css-bsagoj, .css-y1dozs, .css-14lia44, .css-1ks1325 {
    background-color: rgb(24, 26, 27) !important;
}
.code {
    background-color: #393f40 !important;
}
```
