### ISSUE TITLE
PDFs aren't darkened in Microsoft Edge

### ISSUE THREAD

**Issue by Lorenzo-Effe** [darkreader/darkreader#8689]
# Bug Report

## Website Address
Every PDF

## Bug Description
Opening a PDF in Microsoft Edge with Dark Mode doesn't darken the PDF, even if the "Allow access to file URLs" option is enabled from Edge's extension settings.

## Steps To Reproduce
- Open a PDF in Microsoft Edge
- Dark reader will say that the PDF is being darken, but it'll be the same.

## Expected Behavior
The PDF will be dark

## Actual Behavior
The PDF remains the same

## Screenshots
![image](https://user-images.githubusercontent.com/80783030/163964327-5c9c7970-ddd5-472c-92f5-1233c97e1095.png)

## System Information

- OS: Windows 11 Home 21H2, Build 22000.613
- Browser: Microsoft Edge 100.0.1185.44
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
See #4497

**Comment by Lorenzo-Effe** [comment]
Even enabling the "Allow access to file URLs" checkbox, unfortunately the problem remains

**Comment by Gusted** [comment]
4.9.48 might contain the fix for you: https://github.com/darkreader/darkreader/blob/master/CHANGELOG.md#4948-apr-18-2022

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
