### ISSUE TITLE
[Broken Website] docs.expo.dev

### ISSUE THREAD

**Issue by Myzel394** [darkreader/darkreader#8778]
# Broken Website Report

## Website Address

https://docs.expo.dev/versions/latest/sdk/map-view/

## Problematic Observation

SVGs are not visible

## System Information

- OS:  Linux
- Browser:  Firefox
- Dark Reader Version:  4.9.48

## Additional Context

Took a look at the source code. This snippet is replacing the color:

```CSS
[data-darkreader-inline-fill] {
    fill: var(--darkreader-inline-fill) !important;
}
```

Since alphabetical preservation is required, I couldn't overwrite this rule. Here's my snippet:

```CSS
================================

docs.expo.dev

CSS
td > svg > circle, td > svg > path {
    fill: inherit !important;
}

================================
```
