### ISSUE TITLE
[Feature Request] Disable on pdfs

### ISSUE THREAD

**Issue by isaacdoescodes** [darkreader/darkreader#8846]
# Feature Request

## Is this feature request related to a problem?
Yes, if a website opens chrome's pdf window it makes the pdf window light.

## Screenshots
<img width="1438" alt="Screenshot 2022-05-08 at 10 36 28" src="https://user-images.githubusercontent.com/76838845/167290432-1b22eda9-09e1-4244-9e2b-a3a800f80b35.png">

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
