### ISSUE TITLE
PDF in Firefox: This page is protected by browser

### ISSUE THREAD

**Issue by damodaranudas** [darkreader/darkreader#8954]
Uh, oh yeah PDF is for Firefox disabled as they already don't allow us to style any .pdf

_Originally posted by @Gusted in https://github.com/darkreader/darkreader/issues/2856#issuecomment-643686219_

The issue is 2 years old, is the new Firefox also restricted to invert PDFs with dark reader? Is there any tweak at about:config to allow this important feature?

**Comment by Gusted** [comment]
The page is protected, no exceptions for addons.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
