### ISSUE TITLE
[Broken Website] metrobyt-mobile.com

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#9177]
# Broken Website Report

## Website Address
https://www.metrobyt-mobile.com/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the logo in the screenshot needs fixing.
Notice the missing images / background images in the screenshot need fixing.

## Problematic Observation
Logo
Missing Images / Background Images

## Screenshots
![1](https://user-images.githubusercontent.com/95879668/177015825-99570012-a36e-4260-844b-ceed861e0aca.png)

![2](https://user-images.githubusercontent.com/95879668/177015827-f77597a3-e1a2-4cf8-98ef-f10a0f9a7e71.png)

![3](https://user-images.githubusercontent.com/95879668/177015829-8426de04-b390-41fc-b6a0-7f4610f325d5.png)

![4](https://user-images.githubusercontent.com/95879668/177015830-1bcc95f2-1a96-42c8-8d8f-c1262a7d4515.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 104
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
This will be a hard one to fix, got an instant access denied. Likely a geo block :/
![image](https://user-images.githubusercontent.com/25481501/177018133-d46926f7-c273-46c8-9322-9e46551747e8.png)

**Comment by Gusted** [comment]
So I pulled out my trusted browser TOR and was able to visit the page.
Could you conform that the following fix will make the main background-image visible again:

```CSS
metrobyt-mobile.com

CSS
#Desktop-img {
    z-index: 0 !important;
}
```

**Comment by Gusted** [comment]
Eh seems like the images themselves includes the light background. Those are the hardest to fix, not really anything that can be done other than lowering the brightness of the images.

**Comment by Gusted** [comment]
Could you test if this works

```CSS
metrobyt-mobile.com

INVERT
#digital-header-logo-img

CSS
#Desktop-img {
    z-index: 0 !important;
}
```
