### ISSUE TITLE
[Bug] Dark Reader Fails to Render PDFs Inverted or Dark Mode

### ISSUE THREAD

**Issue by geedogz** [darkreader/darkreader#9632]
- Can the issue be reproduced in a fresh browser profile?
      - Yes
  - Is there an existing issue about this?
      - No

## Website Address
Any site that shows a PDF

## Bug Description
PDFs are not rendered in dark mode.

## Steps To Reproduce
PDFs have white background and are not rendered in dark mode.

## Expected Behavior
PDFs should render inverted or dark mode

## System Information
Firefox 103.02.... Dark Reader v4.9.56

- OS: Win 10
- Browser: Firefox 103.02
- Dark Reader Version:  4.9.56

**Comment by Gusted** [comment]
It's an protected page, so Dark Reader cannot modify it, as indicated in Dark Reader's popup.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
