### ISSUE TITLE
[Bug] DARK READER CANNOT REDNER PDF IN DARK MODE

### ISSUE THREAD

**Issue by geedogz** [darkreader/darkreader#9637]
# Bug Report

## Bug Description
PDFs cant be rendered in dark mode

## Expected Behavior
I expect background of PDF to be dark and font white

## Actual Behavior
PDFs are not rendered in dark mode

## System Information
Firefox 103.0.2 and dark reader 4.9.56
  Please do an online search for help if you are not familiar with how to get this information.
-->

- OS: win 10
- Browser: Firefox 103.0.2 
- Dark Reader Version:  4.9.34

**Comment by Gusted** [comment]
I've already commented on your other issue, it's not possible. Please don't open another issue about this.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
