### ISSUE TITLE
Malformed SVG background-image url()

### ISSUE THREAD

**Issue by stanio** [darkreader/darkreader#9862]
# Broken Website Report

## Website Address

https://stanio.github.io/xbrz-java/apidocs/

## Steps To Reproduce

-   Go to https://stanio.github.io/xbrz-java/apidocs/
-   Observe the links in the "See Also" list

## Problematic Observation

The links are lacking "external indicator" image, otherwise seen with the default style (Dark Reader: Off).

## Screenshots

![darkreader](https://user-images.githubusercontent.com/1247730/191054819-8cb39dd8-6e46-410d-9cd7-125c0bf071af.png)

![default](https://user-images.githubusercontent.com/1247730/191054897-5f653690-191a-4728-9f7f-882b535a6dc3.png)

## System Information

- OS: Windows 10
- Browser: Firefox 105.0b9, Edge 105.0.1343.42
- Dark Reader Version: 4.9.57

## Additional Context

The [original style](https://stanio.github.io/xbrz-java/apidocs/stylesheet.css) of these links:

```css
/*
 * Indicator icon for external links.
 */
main a[href*="://"]::after {
    background-image:url('data:image/svg+xml; utf8, \
      <svg xmlns="http://www.w3.org/2000/svg" width="768" height="768">\
        <path d="M584 664H104V184h216V80H0v688h688V448H584zM384 0l132 \
        132-240 240 120 120 240-240 132 132V0z" fill="%234a6782"/>\
      </svg>');
}
```

Dark Reader appears to generate:

```css
main a[href*="://"]::after {
  background-image: url("https://stanio.github.io/xbrz-java/apidocs/url('data:image/svg+xml;%20utf8,%20/%20%20%20%20%20%20%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%22768%22%20height=%22768%22%3E/%20%20%20%20%20%20%20%20%3Cpath%20d=%22M584%20664H104V184h216V80H0v688h688V448H584zM384%200l132%20/%20%20%20%20%20%20%20%20132-240%20240%20120%20120%20240-240%20132%20132V0z%22%20fill=%22%234a6782%22/%3E/%20%20%20%20%20%20%3C/svg%3E')");
}
```

-   Doubles `url("<base-uri>/url('...')")`
-   Replaces `\` (backslash) followed by a newline in the original value with `/` (forward slash) and drops the newline
-   Doesn't adjust the `fill` attribute value in the SVG
